echo +bbbdbtbbbj | sed -nE "/^.{4}b/p; /^.{6}b/p" | wc -l
echo +ggvggbgggstg | sed -nE "/^.{1}g/p; /^.{6}g/p" | wc -l
echo +lssss | sed -nE "/^.{1}s/p; /^.{4}s/p" | wc -l
echo +hvvcvvvvvvvvvsvvv | sed -nE "/^.{13}v/p; /^.{14}v/p" | wc -l
echo +lcmmm | sed -nE "/^.{3}m/p; /^.{5}m/p" | wc -l
echo +stht | sed -nE "/^.{3}t/p; /^.{4}t/p" | wc -l
echo +dbkbhb | sed -nE "/^.{5}b/p; /^.{6}b/p" | wc -l
echo +ppfppppq | sed -nE "/^.{4}p/p; /^.{7}p/p" | wc -l
echo +jjjjj | sed -nE "/^.{4}j/p; /^.{5}j/p" | wc -l
echo +sskssssssssss | sed -nE "/^.{3}s/p; /^.{12}s/p" | wc -l
echo +zrndzbmrzzpzzqzj | sed -nE "/^.{14}z/p; /^.{15}z/p" | wc -l
echo +tllllllllllllplllbl | sed -nE "/^.{12}l/p; /^.{18}l/p" | wc -l
echo +bdbvqbtbrb | sed -nE "/^.{8}b/p; /^.{10}b/p" | wc -l
echo +tcqccc | sed -nE "/^.{1}c/p; /^.{3}c/p" | wc -l
echo +nbnj | sed -nE "/^.{1}n/p; /^.{2}n/p" | wc -l
echo +ccccccccc | sed -nE "/^.{5}c/p; /^.{7}c/p" | wc -l
echo +hpmslrlgll | sed -nE "/^.{9}l/p; /^.{10}l/p" | wc -l
echo +nnnnnnnnb | sed -nE "/^.{6}n/p; /^.{9}n/p" | wc -l
echo +rmzjlrsxkbw | sed -nE "/^.{6}r/p; /^.{10}r/p" | wc -l
echo +bzqnnrrrj | sed -nE "/^.{6}r/p; /^.{8}r/p" | wc -l
echo +mfffvcbtchzrqcn | sed -nE "/^.{4}c/p; /^.{14}c/p" | wc -l
echo +ffffffffffffff | sed -nE "/^.{1}f/p; /^.{6}f/p" | wc -l
echo +wxtkf | sed -nE "/^.{2}f/p; /^.{5}f/p" | wc -l
echo +rdcbbjbzbbpb | sed -nE "/^.{8}b/p; /^.{12}b/p" | wc -l
echo +ddtdddddddwvdfdsdd | sed -nE "/^.{8}d/p; /^.{18}d/p" | wc -l
echo +sssmsgpgszms | sed -nE "/^.{5}s/p; /^.{8}s/p" | wc -l
echo +xxxxxvxxxxxt | sed -nE "/^.{6}x/p; /^.{11}x/p" | wc -l
echo +jhrnnzpxzngfqrntmnc | sed -nE "/^.{17}n/p; /^.{18}n/p" | wc -l
echo +rrrmrrrrlrrshvrrr | sed -nE "/^.{13}r/p; /^.{14}r/p" | wc -l
echo +hhhhrhh | sed -nE "/^.{4}h/p; /^.{5}h/p" | wc -l
echo +dgwtdsxnncd | sed -nE "/^.{8}d/p; /^.{10}d/p" | wc -l
echo +qqbpqmqgmqwqbqqqxcgq | sed -nE "/^.{9}q/p; /^.{13}q/p" | wc -l
echo +gjjcpgg | sed -nE "/^.{2}g/p; /^.{5}g/p" | wc -l
echo +ttttvttttttrtt | sed -nE "/^.{6}t/p; /^.{12}t/p" | wc -l
echo +hhhhhhhhsh | sed -nE "/^.{3}h/p; /^.{9}h/p" | wc -l
echo +ppppsppppppppppz | sed -nE "/^.{15}p/p; /^.{16}p/p" | wc -l
echo +csccctcccc | sed -nE "/^.{2}c/p; /^.{5}c/p" | wc -l
echo +pppppppppppppnp | sed -nE "/^.{11}p/p; /^.{14}p/p" | wc -l
echo +jvbjjjjrjbjj | sed -nE "/^.{8}j/p; /^.{9}j/p" | wc -l
echo +qklbmbntmvbhxplbbcb | sed -nE "/^.{8}b/p; /^.{16}b/p" | wc -l
echo +jjjjsjmfjjjkhj | sed -nE "/^.{12}j/p; /^.{13}j/p" | wc -l
echo +llckxhfmtznptndcsx | sed -nE "/^.{2}t/p; /^.{13}t/p" | wc -l
echo +dxxxxvxxtt | sed -nE "/^.{6}x/p; /^.{8}x/p" | wc -l
echo +ddht | sed -nE "/^.{3}d/p; /^.{4}d/p" | wc -l
echo +ttdtt | sed -nE "/^.{3}t/p; /^.{4}t/p" | wc -l
echo +rrrrrrrrrrrd | sed -nE "/^.{11}r/p; /^.{12}r/p" | wc -l
echo +hhhhhhhhgh | sed -nE "/^.{9}h/p; /^.{10}h/p" | wc -l
echo +hhhhhhhhhhhhhhnhhh | sed -nE "/^.{3}h/p; /^.{16}h/p" | wc -l
echo +hxhhhdhhhsh | sed -nE "/^.{10}h/p; /^.{11}h/p" | wc -l
echo +jnfnjnn | sed -nE "/^.{1}n/p; /^.{7}n/p" | wc -l
echo +msmnpmpf | sed -nE "/^.{3}m/p; /^.{4}m/p" | wc -l
echo +tpdtttgltvtttztlv | sed -nE "/^.{15}t/p; /^.{17}t/p" | wc -l
echo +vvpsvpgjzvvvvjs | sed -nE "/^.{7}v/p; /^.{10}v/p" | wc -l
echo +pxppg | sed -nE "/^.{1}p/p; /^.{5}p/p" | wc -l
echo +jwhgkgvxcv | sed -nE "/^.{2}w/p; /^.{7}w/p" | wc -l
echo +pxxmjznmrzdsbbmmfj | sed -nE "/^.{13}m/p; /^.{14}m/p" | wc -l
echo +ddddd | sed -nE "/^.{1}d/p; /^.{4}d/p" | wc -l
echo +rrrrrrrrrrrrrwrr | sed -nE "/^.{14}r/p; /^.{16}r/p" | wc -l
echo +klbtzzlrlslgswhljtq | sed -nE "/^.{2}l/p; /^.{5}l/p" | wc -l
echo +qccrcpccccccdccccc | sed -nE "/^.{6}c/p; /^.{12}c/p" | wc -l
echo +llllllllvllllllllkll | sed -nE "/^.{2}l/p; /^.{18}l/p" | wc -l
echo +zzzzzzzzszqzwzrzzzzn | sed -nE "/^.{18}z/p; /^.{20}z/p" | wc -l
echo +cbccclcfcncvqztqc | sed -nE "/^.{5}c/p; /^.{16}c/p" | wc -l
echo +fnwmtsmgpxncnr | sed -nE "/^.{7}m/p; /^.{11}m/p" | wc -l
echo +hpjrhbhkshnchbhpph | sed -nE "/^.{6}h/p; /^.{7}h/p" | wc -l
echo +ssssssssssps | sed -nE "/^.{11}s/p; /^.{12}s/p" | wc -l
echo +jfsmmssssqz | sed -nE "/^.{6}s/p; /^.{9}s/p" | wc -l
echo +llllllllllllllbll | sed -nE "/^.{1}l/p; /^.{15}l/p" | wc -l
echo +gggggwgggpggggggg | sed -nE "/^.{2}g/p; /^.{6}g/p" | wc -l
echo +jjjpjjjjn | sed -nE "/^.{6}j/p; /^.{9}j/p" | wc -l
echo +nnnnnnnnnnnnnn | sed -nE "/^.{9}n/p; /^.{13}n/p" | wc -l
echo +cgntllxnvpkjwxtght | sed -nE "/^.{10}t/p; /^.{13}t/p" | wc -l
echo +xcftbcdcndkgm | sed -nE "/^.{2}f/p; /^.{11}f/p" | wc -l
echo +jjjjjjjjjjjjvj | sed -nE "/^.{10}j/p; /^.{13}j/p" | wc -l
echo +rfrffnsffxqflbffvv | sed -nE "/^.{9}f/p; /^.{17}f/p" | wc -l
echo +kkkkkrwkqckmk | sed -nE "/^.{6}k/p; /^.{11}k/p" | wc -l
echo +zfqqqqqn | sed -nE "/^.{5}q/p; /^.{7}q/p" | wc -l
echo +cfcccvccccckccccv | sed -nE "/^.{12}c/p; /^.{13}c/p" | wc -l
echo +xhzzzzzzzzfzzknzz | sed -nE "/^.{5}z/p; /^.{15}z/p" | wc -l
echo +jkfksvmfjbdffffffff | sed -nE "/^.{18}f/p; /^.{19}f/p" | wc -l
echo +hhhhmhhkhsfdg | sed -nE "/^.{8}h/p; /^.{11}h/p" | wc -l
echo +ssssssdjssssssssssss | sed -nE "/^.{14}s/p; /^.{16}s/p" | wc -l
echo +jtmjhsxqqmmthmtttm | sed -nE "/^.{15}t/p; /^.{16}t/p" | wc -l
echo +hkbjhjhh | sed -nE "/^.{5}h/p; /^.{7}h/p" | wc -l
echo +knprnfnfhhrcnk | sed -nE "/^.{2}n/p; /^.{6}n/p" | wc -l
echo +snwd | sed -nE "/^.{3}w/p; /^.{4}w/p" | wc -l
echo +wwwwnwwwwwwwwwwww | sed -nE "/^.{5}w/p; /^.{11}w/p" | wc -l
echo +bkqjghpktfsk | sed -nE "/^.{2}k/p; /^.{12}k/p" | wc -l
echo +vvvsvvvvvvvvvxv | sed -nE "/^.{14}v/p; /^.{15}v/p" | wc -l
echo +fxwwwwwscwl | sed -nE "/^.{8}w/p; /^.{9}w/p" | wc -l
echo +sbjvvsmdvqknbccxxx | sed -nE "/^.{9}c/p; /^.{15}c/p" | wc -l
echo +tpwjtdnnldthxvn | sed -nE "/^.{6}t/p; /^.{15}t/p" | wc -l
echo +tttttrzmzttjttt | sed -nE "/^.{13}t/p; /^.{15}t/p" | wc -l
echo +mmvmlmmmwfmjx | sed -nE "/^.{3}m/p; /^.{11}m/p" | wc -l
echo +gskssssssscssssqjssl | sed -nE "/^.{13}s/p; /^.{14}s/p" | wc -l
echo +bfnmqlldllp | sed -nE "/^.{5}l/p; /^.{10}l/p" | wc -l
echo +qkwqqqqqqqqqqqrqqqqq | sed -nE "/^.{17}q/p; /^.{18}q/p" | wc -l
echo +rsvrrq | sed -nE "/^.{2}r/p; /^.{5}r/p" | wc -l
echo +jjjdj | sed -nE "/^.{3}j/p; /^.{4}j/p" | wc -l
echo +mtmk | sed -nE "/^.{3}m/p; /^.{4}m/p" | wc -l
echo +vsvkvkrkc | sed -nE "/^.{8}k/p; /^.{9}k/p" | wc -l
echo +ttttttcttttgttt | sed -nE "/^.{10}t/p; /^.{12}t/p" | wc -l
echo +trzw | sed -nE "/^.{3}n/p; /^.{4}n/p" | wc -l
echo +qqmpsqbxkqq | sed -nE "/^.{5}q/p; /^.{11}q/p" | wc -l
echo +sqsssnmwqszfsmv | sed -nE "/^.{13}s/p; /^.{15}s/p" | wc -l
echo +bbbbzvb | sed -nE "/^.{5}b/p; /^.{6}b/p" | wc -l
echo +pjjhpnqpzpmpfpfp | sed -nE "/^.{5}p/p; /^.{13}p/p" | wc -l
echo +mgnwlrw | sed -nE "/^.{4}l/p; /^.{5}l/p" | wc -l
echo +fkzxwkj | sed -nE "/^.{1}k/p; /^.{7}k/p" | wc -l
echo +qgxqqqqqqg | sed -nE "/^.{1}q/p; /^.{10}q/p" | wc -l
echo +ssqssssfss | sed -nE "/^.{8}s/p; /^.{9}s/p" | wc -l
echo +xxcscclccdvcmqcc | sed -nE "/^.{7}c/p; /^.{8}c/p" | wc -l
echo +xdlmzdzxrpmlnt | sed -nE "/^.{2}d/p; /^.{6}d/p" | wc -l
echo +sssssnssgbs | sed -nE "/^.{3}s/p; /^.{9}s/p" | wc -l
echo +sblrrhqrhh | sed -nE "/^.{7}h/p; /^.{10}h/p" | wc -l
echo +xnndnnnfnw | sed -nE "/^.{3}n/p; /^.{5}n/p" | wc -l
echo +vllllqlllhllljxlp | sed -nE "/^.{9}l/p; /^.{10}l/p" | wc -l
echo +ddxzbxk | sed -nE "/^.{2}d/p; /^.{5}d/p" | wc -l
echo +mmmmmmmmmmdmmmmsmmm | sed -nE "/^.{10}m/p; /^.{14}m/p" | wc -l
echo +ffffw | sed -nE "/^.{1}f/p; /^.{2}f/p" | wc -l
echo +wdjhplhrbcxdgpnt | sed -nE "/^.{14}g/p; /^.{15}g/p" | wc -l
echo +klllllll | sed -nE "/^.{1}l/p; /^.{2}l/p" | wc -l
echo +ckkhkkvkkkmkkjkwkkwk | sed -nE "/^.{10}k/p; /^.{11}k/p" | wc -l
echo +ffrhdvftfpjfqffhnfsf | sed -nE "/^.{7}f/p; /^.{9}f/p" | wc -l
echo +kkjksrmkccg | sed -nE "/^.{4}c/p; /^.{5}c/p" | wc -l
echo +rrrrhrrrrr | sed -nE "/^.{5}r/p; /^.{9}r/p" | wc -l
echo +pppppth | sed -nE "/^.{5}p/p; /^.{6}p/p" | wc -l
echo +kpfwzjtchtbndblrvst | sed -nE "/^.{4}t/p; /^.{10}t/p" | wc -l
echo +mllllllnllll | sed -nE "/^.{1}l/p; /^.{5}l/p" | wc -l
echo +rrrvrrrrrrrrzrrg | sed -nE "/^.{13}r/p; /^.{16}r/p" | wc -l
echo +xxfxxxxxxxxsxxxxxsxx | sed -nE "/^.{17}x/p; /^.{18}x/p" | wc -l
echo +rwbnqrngcvpgwwww | sed -nE "/^.{8}w/p; /^.{11}w/p" | wc -l
echo +zzzzzzzzzz | sed -nE "/^.{4}z/p; /^.{8}z/p" | wc -l
echo +bbvvbbbbr | sed -nE "/^.{4}b/p; /^.{9}b/p" | wc -l
echo +qlfhxkx | sed -nE "/^.{2}x/p; /^.{5}x/p" | wc -l
echo +wvptttttttt | sed -nE "/^.{3}t/p; /^.{8}t/p" | wc -l
echo +hmmmmqmm | sed -nE "/^.{1}m/p; /^.{3}m/p" | wc -l
echo +nhhhdvhnhrhhhhnhmdh | sed -nE "/^.{17}h/p; /^.{19}h/p" | wc -l
echo +psszbdpsgfks | sed -nE "/^.{11}s/p; /^.{12}s/p" | wc -l
echo +sssssshs | sed -nE "/^.{6}s/p; /^.{7}s/p" | wc -l
echo +mnkdvnvmxljjtggwcl | sed -nE "/^.{10}l/p; /^.{15}l/p" | wc -l
echo +qjjjjjjjjjjjdj | sed -nE "/^.{1}j/p; /^.{13}j/p" | wc -l
echo +jxvkwhlmlhdtgwvgsdzz | sed -nE "/^.{4}l/p; /^.{9}l/p" | wc -l
echo +ccfghhccccgc | sed -nE "/^.{5}c/p; /^.{9}c/p" | wc -l
echo +vvvvvvvvvvv | sed -nE "/^.{10}v/p; /^.{11}v/p" | wc -l
echo +cntwzshkzvmrnnkr | sed -nE "/^.{7}t/p; /^.{8}t/p" | wc -l
echo +tllllllltllll | sed -nE "/^.{1}l/p; /^.{11}l/p" | wc -l
echo +lllglvctrvllzkllt | sed -nE "/^.{15}l/p; /^.{17}l/p" | wc -l
echo +ncnnp | sed -nE "/^.{3}n/p; /^.{5}n/p" | wc -l
echo +jsqqh | sed -nE "/^.{2}q/p; /^.{3}q/p" | wc -l
echo +hhhhhhhhhvh | sed -nE "/^.{4}h/p; /^.{10}h/p" | wc -l
echo +bbnbbbbbtbbkktbbzdr | sed -nE "/^.{16}b/p; /^.{18}b/p" | wc -l
echo +kbggdhgggggggggggfc | sed -nE "/^.{4}g/p; /^.{6}g/p" | wc -l
echo +cpvcppqpplwpt | sed -nE "/^.{12}p/p; /^.{13}p/p" | wc -l
echo +fvhhbrhpghchhhhhh | sed -nE "/^.{5}h/p; /^.{10}h/p" | wc -l
echo +bbvzn | sed -nE "/^.{2}b/p; /^.{5}b/p" | wc -l
echo +xxxbxnwxxxxzxxh | sed -nE "/^.{14}x/p; /^.{15}x/p" | wc -l
echo +nnfgdglfnntnjqn | sed -nE "/^.{13}n/p; /^.{15}n/p" | wc -l
echo +cfccc | sed -nE "/^.{2}c/p; /^.{4}c/p" | wc -l
echo +vrvvzdvv | sed -nE "/^.{3}v/p; /^.{5}v/p" | wc -l
echo +vvvvvvvvvvvvvvvvvvsv | sed -nE "/^.{17}v/p; /^.{19}v/p" | wc -l
echo +hhhhhhhhhhqhhhhhhhhh | sed -nE "/^.{1}h/p; /^.{20}h/p" | wc -l
echo +qqqtqqqqqqqqqqqqlq | sed -nE "/^.{4}q/p; /^.{15}q/p" | wc -l
echo +hhkhvhhhhwhgk | sed -nE "/^.{11}h/p; /^.{13}h/p" | wc -l
echo +ppvppppppptspf | sed -nE "/^.{8}p/p; /^.{11}p/p" | wc -l
echo +mmmpmmkmdmpkspmg | sed -nE "/^.{8}m/p; /^.{9}m/p" | wc -l
echo +lcmvggm | sed -nE "/^.{1}m/p; /^.{7}m/p" | wc -l
echo +tvfstvvpvzsvcv | sed -nE "/^.{6}v/p; /^.{12}v/p" | wc -l
echo +nnnqnnwrrdzlmnwlznrn | sed -nE "/^.{8}n/p; /^.{9}n/p" | wc -l
echo +msssms | sed -nE "/^.{1}s/p; /^.{5}s/p" | wc -l
echo +vpdzvdvgv | sed -nE "/^.{1}v/p; /^.{3}v/p" | wc -l
echo +drgrfggcg | sed -nE "/^.{6}g/p; /^.{9}g/p" | wc -l
echo +djpxhxvncxfghsxx | sed -nE "/^.{6}x/p; /^.{16}x/p" | wc -l
echo +sjbwwxbvtvbkt | sed -nE "/^.{1}b/p; /^.{3}b/p" | wc -l
echo +cccccstccjhv | sed -nE "/^.{6}c/p; /^.{8}c/p" | wc -l
echo +qqqpqqqqqqwqqq | sed -nE "/^.{1}q/p; /^.{11}q/p" | wc -l
echo +vsbmmmmmmmqmmsm | sed -nE "/^.{9}m/p; /^.{11}m/p" | wc -l
echo +gqggggggg | sed -nE "/^.{2}g/p; /^.{7}g/p" | wc -l
echo +mrgvm | sed -nE "/^.{2}m/p; /^.{3}m/p" | wc -l
echo +cccpcfcc | sed -nE "/^.{6}c/p; /^.{7}c/p" | wc -l
echo +swbngwswnxnww | sed -nE "/^.{6}w/p; /^.{10}w/p" | wc -l
echo +rrrrrrrrrrwrrgrdr | sed -nE "/^.{13}r/p; /^.{14}r/p" | wc -l
echo +vctxhxtfvq | sed -nE "/^.{3}v/p; /^.{9}v/p" | wc -l
echo +jrrcslgplcprlvgthg | sed -nE "/^.{2}r/p; /^.{9}r/p" | wc -l
echo +hnnnsxclvdj | sed -nE "/^.{2}n/p; /^.{3}n/p" | wc -l
echo +zrhghhqhgzh | sed -nE "/^.{10}h/p; /^.{11}h/p" | wc -l
echo +zzzlzzzzzzzzpzqzpzzz | sed -nE "/^.{15}z/p; /^.{18}z/p" | wc -l
echo +fffffrfl | sed -nE "/^.{3}f/p; /^.{8}f/p" | wc -l
echo +rllllfl | sed -nE "/^.{1}l/p; /^.{4}l/p" | wc -l
echo +nnnnnvtnv | sed -nE "/^.{1}n/p; /^.{2}n/p" | wc -l
echo +zzzzzzzzzzzzzzzzzzqz | sed -nE "/^.{17}z/p; /^.{19}z/p" | wc -l
echo +nnnznnnnnnznnnn | sed -nE "/^.{13}n/p; /^.{15}n/p" | wc -l
echo +gcccncjmsncfcntjc | sed -nE "/^.{2}c/p; /^.{5}c/p" | wc -l
echo +hhhhhhhhbpsfh | sed -nE "/^.{8}h/p; /^.{9}h/p" | wc -l
echo +lzvvlbrgjgrr | sed -nE "/^.{7}r/p; /^.{11}r/p" | wc -l
echo +xxxxqxxxxxxx | sed -nE "/^.{5}x/p; /^.{11}x/p" | wc -l
echo +gqpkmppzpsmtzhfdfpl | sed -nE "/^.{4}p/p; /^.{7}p/p" | wc -l
echo +jjdjdg | sed -nE "/^.{3}j/p; /^.{4}j/p" | wc -l
echo +zzzzzzzgjzzzzpzf | sed -nE "/^.{14}z/p; /^.{16}z/p" | wc -l
echo +nnnvnwnnnnh | sed -nE "/^.{1}n/p; /^.{2}n/p" | wc -l
echo +jhzzz | sed -nE "/^.{4}z/p; /^.{5}z/p" | wc -l
echo +kkkkkkf | sed -nE "/^.{5}k/p; /^.{7}k/p" | wc -l
echo +khzzrzjzmzzvzzpcclm | sed -nE "/^.{8}z/p; /^.{18}z/p" | wc -l
echo +kjrhwkhmsm | sed -nE "/^.{5}m/p; /^.{10}m/p" | wc -l
echo +vvvvvvvvvvvvvvvwv | sed -nE "/^.{10}v/p; /^.{16}v/p" | wc -l
echo +xhvjsmllkcdtldfxlw | sed -nE "/^.{9}l/p; /^.{10}l/p" | wc -l
echo +ppjvppbpqhpwhppgbp | sed -nE "/^.{8}p/p; /^.{10}p/p" | wc -l
echo +jlmkhm | sed -nE "/^.{4}m/p; /^.{6}m/p" | wc -l
echo +gvpklkkkk | sed -nE "/^.{1}k/p; /^.{3}k/p" | wc -l
echo +ggjggggvgmgtpgcg | sed -nE "/^.{15}g/p; /^.{16}g/p" | wc -l
echo +jbjwj | sed -nE "/^.{1}j/p; /^.{4}j/p" | wc -l
echo +xxxpxxdxxhfx | sed -nE "/^.{1}x/p; /^.{3}x/p" | wc -l
echo +vxmhhdvvfjjqwhtv | sed -nE "/^.{14}v/p; /^.{16}v/p" | wc -l
echo +lnkchzlwxlp | sed -nE "/^.{6}l/p; /^.{7}l/p" | wc -l
echo +vvvcv | sed -nE "/^.{3}v/p; /^.{4}v/p" | wc -l
echo +pbqpppppzbmppc | sed -nE "/^.{13}p/p; /^.{14}p/p" | wc -l
echo +glqwzprpqbqf | sed -nE "/^.{6}p/p; /^.{12}p/p" | wc -l
echo +lllllglllllll | sed -nE "/^.{6}l/p; /^.{12}l/p" | wc -l
echo +nnsnnnndcn | sed -nE "/^.{8}n/p; /^.{9}n/p" | wc -l
echo +prwppppp | sed -nE "/^.{6}p/p; /^.{8}p/p" | wc -l
echo +dqqqqqqqqjq | sed -nE "/^.{1}q/p; /^.{10}q/p" | wc -l
echo +kwtbdnjqmwwxhwcwswkl | sed -nE "/^.{12}w/p; /^.{16}w/p" | wc -l
echo +rrnjghfrrrshlrq | sed -nE "/^.{11}r/p; /^.{14}r/p" | wc -l
echo +vwbbvcvgnxdmxl | sed -nE "/^.{2}w/p; /^.{14}w/p" | wc -l
echo +sqmggkgslkwlvggg | sed -nE "/^.{7}g/p; /^.{8}g/p" | wc -l
echo +tqqqqqq | sed -nE "/^.{1}q/p; /^.{6}q/p" | wc -l
echo +bbbr | sed -nE "/^.{2}b/p; /^.{3}b/p" | wc -l
echo +jnwbswfpbn | sed -nE "/^.{7}b/p; /^.{9}b/p" | wc -l
echo +nnlct | sed -nE "/^.{4}n/p; /^.{5}n/p" | wc -l
echo +ssssssssssp | sed -nE "/^.{3}s/p; /^.{11}s/p" | wc -l
echo +wjlpwf | sed -nE "/^.{2}f/p; /^.{6}f/p" | wc -l
echo +gggghqgqgb | sed -nE "/^.{5}g/p; /^.{10}g/p" | wc -l
echo +ppdg | sed -nE "/^.{1}p/p; /^.{3}p/p" | wc -l
echo +pjnkjjljjj | sed -nE "/^.{4}j/p; /^.{7}j/p" | wc -l
echo +ghmjzxmtxjxnv | sed -nE "/^.{1}v/p; /^.{2}v/p" | wc -l
echo +klgdzfmgdwhqdkhcnzm | sed -nE "/^.{6}k/p; /^.{14}k/p" | wc -l
echo +tgzpzzzzztc | sed -nE "/^.{6}z/p; /^.{11}z/p" | wc -l
echo +cxsmjbdgdnrb | sed -nE "/^.{2}b/p; /^.{12}b/p" | wc -l
echo +lxdvvh | sed -nE "/^.{4}v/p; /^.{6}v/p" | wc -l
echo +pnpdnrll | sed -nE "/^.{3}l/p; /^.{8}l/p" | wc -l
echo +mzmswvmmbxmzlmwhdvq | sed -nE "/^.{7}m/p; /^.{8}m/p" | wc -l
echo +khzssssssssszsssss | sed -nE "/^.{13}s/p; /^.{14}s/p" | wc -l
echo +dmfdlgcxdbzznbrlqn | sed -nE "/^.{10}d/p; /^.{18}d/p" | wc -l
echo +jjjjjjjjjjjjdpjj | sed -nE "/^.{13}j/p; /^.{14}j/p" | wc -l
echo +jjjjjjjjjwjsqjwjj | sed -nE "/^.{15}j/p; /^.{17}j/p" | wc -l
echo +xxfxkzxxhxxxxxvxxw | sed -nE "/^.{10}x/p; /^.{15}x/p" | wc -l
echo +wcccwcmmcccccxhcccc | sed -nE "/^.{7}c/p; /^.{14}c/p" | wc -l
echo +zmzvfzlszr | sed -nE "/^.{2}z/p; /^.{7}z/p" | wc -l
echo +jjkrklrkkv | sed -nE "/^.{7}k/p; /^.{8}k/p" | wc -l
echo +rrrrrjrtz | sed -nE "/^.{8}r/p; /^.{9}r/p" | wc -l
echo +tvws | sed -nE "/^.{2}w/p; /^.{3}w/p" | wc -l
echo +bbbjm | sed -nE "/^.{1}b/p; /^.{5}b/p" | wc -l
echo +tqqjf | sed -nE "/^.{1}q/p; /^.{2}q/p" | wc -l
echo +wlgjghjhjljwtpcdkqwk | sed -nE "/^.{5}j/p; /^.{10}j/p" | wc -l
echo +dzpkc | sed -nE "/^.{2}c/p; /^.{5}c/p" | wc -l
echo +mbvmkm | sed -nE "/^.{5}m/p; /^.{6}m/p" | wc -l
echo +stjkjvvxrmwdpkwsjqvc | sed -nE "/^.{4}k/p; /^.{15}k/p" | wc -l
echo +hwkgjplmhxwgvnbhwh | sed -nE "/^.{6}h/p; /^.{9}h/p" | wc -l
echo +zzzzzzzzzzzzz | sed -nE "/^.{12}z/p; /^.{13}z/p" | wc -l
echo +qqqqqqqqq | sed -nE "/^.{7}q/p; /^.{8}q/p" | wc -l
echo +clcwmccczclcccc | sed -nE "/^.{2}c/p; /^.{5}c/p" | wc -l
echo +jlcgfbflklvpfqxtwgg | sed -nE "/^.{2}l/p; /^.{5}l/p" | wc -l
echo +nnnnnnvnnnnnn | sed -nE "/^.{5}n/p; /^.{7}n/p" | wc -l
echo +gfktfffqvgltsbff | sed -nE "/^.{3}f/p; /^.{5}f/p" | wc -l
echo +jppbttppzpqppppp | sed -nE "/^.{10}p/p; /^.{16}p/p" | wc -l
echo +zmdm | sed -nE "/^.{2}m/p; /^.{3}m/p" | wc -l
echo +zsmtjjdnrpp | sed -nE "/^.{4}j/p; /^.{6}j/p" | wc -l
echo +hvvmrkfnnkvrjtjhjj | sed -nE "/^.{17}j/p; /^.{18}j/p" | wc -l
echo +dtddddddddtwxgld | sed -nE "/^.{12}d/p; /^.{15}d/p" | wc -l
echo +rdzrwfgrmxwttknxz | sed -nE "/^.{8}r/p; /^.{12}r/p" | wc -l
echo +rssbktxsgd | sed -nE "/^.{6}s/p; /^.{7}s/p" | wc -l
echo +ddddmwddddxddndc | sed -nE "/^.{11}d/p; /^.{13}d/p" | wc -l
echo +ppcpspfp | sed -nE "/^.{3}p/p; /^.{6}p/p" | wc -l
echo +jjjjjjgjjjjcjlzj | sed -nE "/^.{12}j/p; /^.{15}j/p" | wc -l
echo +tgjkwfbsxzzvvpmfs | sed -nE "/^.{8}v/p; /^.{12}v/p" | wc -l
echo +trbfbdz | sed -nE "/^.{6}z/p; /^.{7}z/p" | wc -l
echo +vvvvvpvv | sed -nE "/^.{4}v/p; /^.{6}v/p" | wc -l
echo +pnvppdpjppppppph | sed -nE "/^.{8}p/p; /^.{16}p/p" | wc -l
echo +lzzzzpdzk | sed -nE "/^.{8}z/p; /^.{9}z/p" | wc -l
echo +qttzz | sed -nE "/^.{1}t/p; /^.{4}t/p" | wc -l
echo +dhdd | sed -nE "/^.{2}d/p; /^.{3}d/p" | wc -l
echo +mmmkmmxmkj | sed -nE "/^.{5}m/p; /^.{8}m/p" | wc -l
echo +hfhzkwdmrlqvfkn | sed -nE "/^.{2}f/p; /^.{12}f/p" | wc -l
echo +hhhhhph | sed -nE "/^.{5}h/p; /^.{6}h/p" | wc -l
echo +bbbbxbbbbbbbbbh | sed -nE "/^.{14}b/p; /^.{15}b/p" | wc -l
echo +vvcj | sed -nE "/^.{2}v/p; /^.{3}v/p" | wc -l
echo +ddvdwwqdddcdtdmwdqp | sed -nE "/^.{12}d/p; /^.{19}d/p" | wc -l
echo +ssjssssssss | sed -nE "/^.{3}s/p; /^.{4}s/p" | wc -l
echo +wzzxqcdcnlgcph | sed -nE "/^.{2}c/p; /^.{6}c/p" | wc -l
echo +jjdrcjzjkjcs | sed -nE "/^.{11}j/p; /^.{12}j/p" | wc -l
echo +bzzzzzzxzz | sed -nE "/^.{4}z/p; /^.{9}z/p" | wc -l
echo +gjbfkxhb | sed -nE "/^.{2}b/p; /^.{8}b/p" | wc -l
echo +cpksst | sed -nE "/^.{1}c/p; /^.{3}c/p" | wc -l
echo +hhjhh | sed -nE "/^.{1}h/p; /^.{5}h/p" | wc -l
echo +jjjjjjjjjjjjjjr | sed -nE "/^.{14}j/p; /^.{15}j/p" | wc -l
echo +pcndxcfknfbnnls | sed -nE "/^.{8}n/p; /^.{9}n/p" | wc -l
echo +kkkqzkwbkkkrtn | sed -nE "/^.{10}k/p; /^.{13}k/p" | wc -l
echo +rzrrrnrj | sed -nE "/^.{4}r/p; /^.{5}r/p" | wc -l
echo +ppppppppppppppt | sed -nE "/^.{13}p/p; /^.{15}p/p" | wc -l
echo +fjqqzzzjm | sed -nE "/^.{3}j/p; /^.{6}j/p" | wc -l
echo +zmjhctkmf | sed -nE "/^.{2}m/p; /^.{9}m/p" | wc -l
echo +ssmjss | sed -nE "/^.{5}s/p; /^.{6}s/p" | wc -l
echo +jlfd | sed -nE "/^.{3}c/p; /^.{4}c/p" | wc -l
echo +qbddfhnddzgvddddd | sed -nE "/^.{8}d/p; /^.{12}d/p" | wc -l
echo +xfppppcppppxgp | sed -nE "/^.{6}p/p; /^.{7}p/p" | wc -l
echo +sssssssfssssssss | sed -nE "/^.{8}s/p; /^.{13}s/p" | wc -l
echo +xskktsjxlvgfxtzzgfj | sed -nE "/^.{13}g/p; /^.{17}g/p" | wc -l
echo +qqtwfqqnkvbvbhzs | sed -nE "/^.{2}q/p; /^.{4}q/p" | wc -l
echo +cjmjs | sed -nE "/^.{1}j/p; /^.{5}j/p" | wc -l
echo +tvccnc | sed -nE "/^.{4}c/p; /^.{5}c/p" | wc -l
echo +kkfhmnkkmztxtmn | sed -nE "/^.{3}m/p; /^.{14}m/p" | wc -l
echo +xxxxxpxmxxvbxxxvx | sed -nE "/^.{11}x/p; /^.{15}x/p" | wc -l
echo +nhgzwmmrkqhblnk | sed -nE "/^.{9}l/p; /^.{11}l/p" | wc -l
echo +xxxxxdmxxxxxxxx | sed -nE "/^.{7}x/p; /^.{10}x/p" | wc -l
echo +vvvvvvpvvvjvvcvv | sed -nE "/^.{13}v/p; /^.{14}v/p" | wc -l
echo +nnnnqnnbnnnnnnnpn | sed -nE "/^.{16}n/p; /^.{17}n/p" | wc -l
echo +jvjj | sed -nE "/^.{3}j/p; /^.{4}j/p" | wc -l
echo +zlqsgvpztknqjqqwqvf | sed -nE "/^.{15}q/p; /^.{16}q/p" | wc -l
echo +sssrsssdss | sed -nE "/^.{3}s/p; /^.{4}s/p" | wc -l
echo +ggqggmggswggdk | sed -nE "/^.{11}g/p; /^.{13}g/p" | wc -l
echo +jmtzttztqt | sed -nE "/^.{1}t/p; /^.{4}t/p" | wc -l
echo +vvvv | sed -nE "/^.{2}v/p; /^.{3}v/p" | wc -l
echo +cgjgxgggkgbggxg | sed -nE "/^.{11}g/p; /^.{13}g/p" | wc -l
echo +ggggqlhgmz | sed -nE "/^.{4}g/p; /^.{6}g/p" | wc -l
echo +prvxwzkvdhgkjlg | sed -nE "/^.{8}g/p; /^.{15}g/p" | wc -l
echo +gggggnsjlg | sed -nE "/^.{6}g/p; /^.{9}g/p" | wc -l
echo +mmvlpzkmpgtpvj | sed -nE "/^.{12}p/p; /^.{14}p/p" | wc -l
echo +kkkxkkjkkkdkkkp | sed -nE "/^.{7}k/p; /^.{10}k/p" | wc -l
echo +zmztqsrgvjjmswzkbnk | sed -nE "/^.{14}b/p; /^.{16}b/p" | wc -l
echo +xxbxxxxhx | sed -nE "/^.{1}x/p; /^.{2}x/p" | wc -l
echo +tlhsx | sed -nE "/^.{2}l/p; /^.{5}l/p" | wc -l
echo +xxxxn | sed -nE "/^.{3}x/p; /^.{5}x/p" | wc -l
echo +vdnmtmqwnxkcldc | sed -nE "/^.{4}c/p; /^.{12}c/p" | wc -l
echo +xxxxjglx | sed -nE "/^.{4}x/p; /^.{8}x/p" | wc -l
echo +vsssspszssssnsss | sed -nE "/^.{5}s/p; /^.{13}s/p" | wc -l
echo +kkhkkkknb | sed -nE "/^.{3}k/p; /^.{6}k/p" | wc -l
echo +pttqtwnprt | sed -nE "/^.{3}t/p; /^.{5}t/p" | wc -l
echo +ttjqvzmgmmjqzkd | sed -nE "/^.{10}m/p; /^.{14}m/p" | wc -l
echo +bbbbpbbb | sed -nE "/^.{1}b/p; /^.{5}b/p" | wc -l
echo +wdjrhvfngdtlkdl | sed -nE "/^.{10}d/p; /^.{15}d/p" | wc -l
echo +trxwdwww | sed -nE "/^.{6}w/p; /^.{7}w/p" | wc -l
echo +snxqlgtsmdnnjgwrgmms | sed -nE "/^.{2}n/p; /^.{4}n/p" | wc -l
echo +klslpljllqlcslqqll | sed -nE "/^.{16}l/p; /^.{18}l/p" | wc -l
echo +tttwzttjt | sed -nE "/^.{4}t/p; /^.{7}t/p" | wc -l
echo +ffffffffwf | sed -nE "/^.{9}f/p; /^.{10}f/p" | wc -l
echo +trhgxjchhxvvhqp | sed -nE "/^.{8}h/p; /^.{15}h/p" | wc -l
echo +wwwwwwwqwwwg | sed -nE "/^.{8}w/p; /^.{12}w/p" | wc -l
echo +xxxxxxxxsffqlxx | sed -nE "/^.{12}x/p; /^.{13}x/p" | wc -l
echo +kkkklkkkktkk | sed -nE "/^.{5}k/p; /^.{7}k/p" | wc -l
echo +wkmmqmmhf | sed -nE "/^.{1}m/p; /^.{7}m/p" | wc -l
echo +mhhchwhhhzhhcvh | sed -nE "/^.{12}h/p; /^.{13}h/p" | wc -l
echo +kkkkkkwkkkgkk | sed -nE "/^.{7}k/p; /^.{11}k/p" | wc -l
echo +hdlbll | sed -nE "/^.{4}l/p; /^.{6}l/p" | wc -l
echo +fvvvvvvvrvvv | sed -nE "/^.{8}v/p; /^.{12}v/p" | wc -l
echo +hzhhhhhhhhhhhhr | sed -nE "/^.{2}h/p; /^.{9}h/p" | wc -l
echo +qbqjpbbbdsshv | sed -nE "/^.{6}b/p; /^.{8}b/p" | wc -l
echo +hwhl | sed -nE "/^.{2}h/p; /^.{3}h/p" | wc -l
echo +mdllxjgdw | sed -nE "/^.{4}l/p; /^.{7}l/p" | wc -l
echo +rwffzfkpwbzp | sed -nE "/^.{3}f/p; /^.{9}f/p" | wc -l
echo +ttnttt | sed -nE "/^.{3}t/p; /^.{5}t/p" | wc -l
echo +mpcccpndqc | sed -nE "/^.{7}c/p; /^.{10}c/p" | wc -l
echo +fhhhljh | sed -nE "/^.{6}h/p; /^.{7}h/p" | wc -l
echo +pnvzcns | sed -nE "/^.{2}v/p; /^.{7}v/p" | wc -l
echo +vvgv | sed -nE "/^.{1}v/p; /^.{3}v/p" | wc -l
echo +ssssshsspsssssss | sed -nE "/^.{5}s/p; /^.{9}s/p" | wc -l
echo +mjjjjq | sed -nE "/^.{4}j/p; /^.{6}j/p" | wc -l
echo +hwbqghmvmmnvhhrqmj | sed -nE "/^.{5}h/p; /^.{14}h/p" | wc -l
echo +wctjsh | sed -nE "/^.{5}s/p; /^.{6}s/p" | wc -l
echo +sssscsjs | sed -nE "/^.{7}s/p; /^.{8}s/p" | wc -l
echo +vvvvvvvvvvvvvvvvv | sed -nE "/^.{14}v/p; /^.{17}v/p" | wc -l
echo +wxwwwwwwfwwwwsw | sed -nE "/^.{14}w/p; /^.{15}w/p" | wc -l
echo +ksvvvlpvv | sed -nE "/^.{6}v/p; /^.{7}v/p" | wc -l
echo +cssstsvsscshsstsss | sed -nE "/^.{7}s/p; /^.{18}s/p" | wc -l
echo +zzwbpm | sed -nE "/^.{5}b/p; /^.{6}b/p" | wc -l
echo +bvtmpkxspskr | sed -nE "/^.{6}r/p; /^.{7}r/p" | wc -l
echo +lvxrvqv | sed -nE "/^.{6}v/p; /^.{7}v/p" | wc -l
echo +ccccccccccccccccccc | sed -nE "/^.{15}c/p; /^.{17}c/p" | wc -l
echo +ghxpwhxcqjrr | sed -nE "/^.{8}r/p; /^.{12}r/p" | wc -l
echo +kzbcdkndqm | sed -nE "/^.{6}k/p; /^.{10}k/p" | wc -l
echo +tpsxss | sed -nE "/^.{5}s/p; /^.{6}s/p" | wc -l
echo +qlrlp | sed -nE "/^.{1}p/p; /^.{5}p/p" | wc -l
echo +qqqkqqqz | sed -nE "/^.{4}q/p; /^.{8}q/p" | wc -l
echo +vgvsxvwvlxv | sed -nE "/^.{7}v/p; /^.{11}v/p" | wc -l
echo +bgkbb | sed -nE "/^.{2}b/p; /^.{5}b/p" | wc -l
echo +jjsplxjxgqjfjrjxjjlx | sed -nE "/^.{3}j/p; /^.{18}j/p" | wc -l
echo +kxkhkkjkkrvkkk | sed -nE "/^.{6}k/p; /^.{10}k/p" | wc -l
echo +ttttttzttttttttbtttt | sed -nE "/^.{7}t/p; /^.{16}t/p" | wc -l
echo +ptzptslrjgwlfgwq | sed -nE "/^.{1}l/p; /^.{7}l/p" | wc -l
echo +vvqvvvvvvvv | sed -nE "/^.{8}v/p; /^.{10}v/p" | wc -l
echo +zzzhz | sed -nE "/^.{3}z/p; /^.{5}z/p" | wc -l
echo +cbrctgc | sed -nE "/^.{6}c/p; /^.{7}c/p" | wc -l
echo +llllxlllllllllllll | sed -nE "/^.{5}l/p; /^.{16}l/p" | wc -l
echo +chxclqcdrh | sed -nE "/^.{6}c/p; /^.{7}c/p" | wc -l
echo +jcmcccccwcccccjbvc | sed -nE "/^.{1}c/p; /^.{10}c/p" | wc -l
echo +zhhvhhhhhhhhhv | sed -nE "/^.{8}h/p; /^.{14}h/p" | wc -l
echo +rnnnnnfnnnnnvn | sed -nE "/^.{4}n/p; /^.{7}n/p" | wc -l
echo +wwwwwwwsgtwww | sed -nE "/^.{10}w/p; /^.{12}w/p" | wc -l
echo +cmbcctzcj | sed -nE "/^.{5}c/p; /^.{8}c/p" | wc -l
echo +fffskrf | sed -nE "/^.{5}f/p; /^.{7}f/p" | wc -l
echo +lllmzl | sed -nE "/^.{5}l/p; /^.{6}l/p" | wc -l
echo +mmmmmmmmmmmmmmmmmmm | sed -nE "/^.{7}m/p; /^.{14}m/p" | wc -l
echo +jfffffffzvffff | sed -nE "/^.{1}f/p; /^.{9}f/p" | wc -l
echo +ggmng | sed -nE "/^.{2}g/p; /^.{5}g/p" | wc -l
echo +xxxxxxxxxxxxxxxlx | sed -nE "/^.{16}x/p; /^.{17}x/p" | wc -l
echo +npkgjcfnnnnn | sed -nE "/^.{4}n/p; /^.{10}n/p" | wc -l
echo +bhkjgsnzxkdgwbdv | sed -nE "/^.{1}d/p; /^.{13}d/p" | wc -l
echo +ncqfzff | sed -nE "/^.{6}f/p; /^.{7}f/p" | wc -l
echo +hqhhhhhjhhh | sed -nE "/^.{7}h/p; /^.{10}h/p" | wc -l
echo +vnvvv | sed -nE "/^.{2}v/p; /^.{4}v/p" | wc -l
echo +thlmdwgwgtswvtx | sed -nE "/^.{1}w/p; /^.{6}w/p" | wc -l
echo +ddlkhvfdnpbdr | sed -nE "/^.{3}d/p; /^.{7}d/p" | wc -l
echo +qbfq | sed -nE "/^.{1}q/p; /^.{4}q/p" | wc -l
echo +rzfmfrjgcfjk | sed -nE "/^.{2}f/p; /^.{6}f/p" | wc -l
echo +bbbbblbbbkbbbbbbwqb | sed -nE "/^.{10}b/p; /^.{16}b/p" | wc -l
echo +jjhcjnkgvrnwjp | sed -nE "/^.{13}j/p; /^.{14}j/p" | wc -l
echo +lgqwvrlwcllllv | sed -nE "/^.{5}l/p; /^.{12}l/p" | wc -l
echo +jjgpdjssspjfdbt | sed -nE "/^.{4}j/p; /^.{8}j/p" | wc -l
echo +hhhhhhhhwhhh | sed -nE "/^.{1}h/p; /^.{9}h/p" | wc -l
echo +psmppt | sed -nE "/^.{4}p/p; /^.{6}p/p" | wc -l
echo +zhhhk | sed -nE "/^.{2}h/p; /^.{3}h/p" | wc -l
echo +bbbbbmbbvb | sed -nE "/^.{2}b/p; /^.{6}b/p" | wc -l
echo +zzzzzzgzdzz | sed -nE "/^.{7}z/p; /^.{9}z/p" | wc -l
echo +ddgdmdwddd | sed -nE "/^.{8}d/p; /^.{9}d/p" | wc -l
echo +nssssv | sed -nE "/^.{2}s/p; /^.{6}s/p" | wc -l
echo +xxxxxxxxxxxxxxxxxvxx | sed -nE "/^.{18}x/p; /^.{20}x/p" | wc -l
echo +dzckmrbhcmwvkcxmlx | sed -nE "/^.{9}m/p; /^.{10}m/p" | wc -l
echo +vwvvvvwvvghvn | sed -nE "/^.{10}v/p; /^.{11}v/p" | wc -l
echo +wcwxddjhnljfntj | sed -nE "/^.{3}d/p; /^.{6}d/p" | wc -l
echo +vvvvvvvvvvvvcvc | sed -nE "/^.{13}v/p; /^.{15}v/p" | wc -l
echo +xxfxfxxkx | sed -nE "/^.{1}x/p; /^.{5}x/p" | wc -l
echo +wqzjzwwwtw | sed -nE "/^.{7}w/p; /^.{8}w/p" | wc -l
echo +flgl | sed -nE "/^.{2}f/p; /^.{4}f/p" | wc -l
echo +ncfngngdnm | sed -nE "/^.{3}n/p; /^.{6}n/p" | wc -l
echo +kdkmbkkkkxk | sed -nE "/^.{5}k/p; /^.{7}k/p" | wc -l
echo +xxvxth | sed -nE "/^.{5}x/p; /^.{6}x/p" | wc -l
echo +rrhhzr | sed -nE "/^.{5}r/p; /^.{6}r/p" | wc -l
echo +bbbrbbbbbmb | sed -nE "/^.{4}b/p; /^.{6}b/p" | wc -l
echo +qqqqqqqqqzqkqp | sed -nE "/^.{12}q/p; /^.{13}q/p" | wc -l
echo +mlbflnrbhlhpdrfln | sed -nE "/^.{6}n/p; /^.{14}n/p" | wc -l
echo +qqqqqqqqqqqwq | sed -nE "/^.{9}q/p; /^.{12}q/p" | wc -l
echo +rkncnbk | sed -nE "/^.{3}k/p; /^.{4}k/p" | wc -l
echo +jjpj | sed -nE "/^.{1}j/p; /^.{3}j/p" | wc -l
echo +vjvczrvvm | sed -nE "/^.{8}v/p; /^.{9}v/p" | wc -l
echo +tmnmmmxmbmmmrtmmr | sed -nE "/^.{9}m/p; /^.{16}m/p" | wc -l
echo +qqqqqzqqsjxq | sed -nE "/^.{9}q/p; /^.{11}q/p" | wc -l
echo +hhhhcs | sed -nE "/^.{3}h/p; /^.{5}h/p" | wc -l
echo +kkkkkkkkkkkvqk | sed -nE "/^.{11}k/p; /^.{12}k/p" | wc -l
echo +xlxxxjjxxxpx | sed -nE "/^.{11}x/p; /^.{12}x/p" | wc -l
echo +nngtnhlnjfnf | sed -nE "/^.{1}n/p; /^.{12}n/p" | wc -l
echo +ppptppppp | sed -nE "/^.{5}p/p; /^.{7}p/p" | wc -l
echo +lllmlflllhllpm | sed -nE "/^.{13}l/p; /^.{14}l/p" | wc -l
echo +vdkmrdfzmkknmp | sed -nE "/^.{13}m/p; /^.{14}m/p" | wc -l
echo +ssssssqssssscssss | sed -nE "/^.{13}s/p; /^.{15}s/p" | wc -l
echo +hhhlxhhhhhhshh | sed -nE "/^.{5}h/p; /^.{11}h/p" | wc -l
echo +ssssssssssgsssss | sed -nE "/^.{10}s/p; /^.{11}s/p" | wc -l
echo +kqqqqmqnqq | sed -nE "/^.{6}q/p; /^.{7}q/p" | wc -l
echo +llllllltlllljll | sed -nE "/^.{8}l/p; /^.{13}l/p" | wc -l
echo +jjjjjjjjjjjlj | sed -nE "/^.{9}j/p; /^.{12}j/p" | wc -l
echo +gstcncsssscssssss | sed -nE "/^.{7}s/p; /^.{11}s/p" | wc -l
echo +lrtjfnhmpmxj | sed -nE "/^.{4}x/p; /^.{6}x/p" | wc -l
echo +cttccccccnccclcccccc | sed -nE "/^.{9}c/p; /^.{20}c/p" | wc -l
echo +cwwwwwwwwww | sed -nE "/^.{1}w/p; /^.{8}w/p" | wc -l
echo +nnnnnnnngnnnnn | sed -nE "/^.{12}n/p; /^.{13}n/p" | wc -l
echo +pfqwcpnppppwwpqppp | sed -nE "/^.{1}p/p; /^.{5}p/p" | wc -l
echo +gggsgglghg | sed -nE "/^.{7}g/p; /^.{8}g/p" | wc -l
echo +gggggggg | sed -nE "/^.{6}g/p; /^.{7}g/p" | wc -l
echo +ssssssssssss | sed -nE "/^.{4}s/p; /^.{10}s/p" | wc -l
echo +njsnnln | sed -nE "/^.{1}n/p; /^.{2}n/p" | wc -l
echo +gzczzwdzkkzz | sed -nE "/^.{7}z/p; /^.{8}z/p" | wc -l
echo +bbbwjfbh | sed -nE "/^.{2}b/p; /^.{8}b/p" | wc -l
echo +rrrrbrrbr | sed -nE "/^.{6}r/p; /^.{8}r/p" | wc -l
echo +lkkkkl | sed -nE "/^.{2}k/p; /^.{5}k/p" | wc -l
echo +swcgjcm | sed -nE "/^.{2}c/p; /^.{3}c/p" | wc -l
echo +ttttttttttt | sed -nE "/^.{2}t/p; /^.{10}t/p" | wc -l
echo +lllllxllllllqhl | sed -nE "/^.{12}l/p; /^.{13}l/p" | wc -l
echo +qtqxdpqqlwhqwlr | sed -nE "/^.{2}l/p; /^.{9}l/p" | wc -l
echo +qqxrn | sed -nE "/^.{1}q/p; /^.{5}q/p" | wc -l
echo +kkkkkkkkkckk | sed -nE "/^.{10}k/p; /^.{11}k/p" | wc -l
echo +ffff | sed -nE "/^.{1}f/p; /^.{2}f/p" | wc -l
echo +rrxr | sed -nE "/^.{3}r/p; /^.{4}r/p" | wc -l
echo +lppppxpsp | sed -nE "/^.{8}p/p; /^.{9}p/p" | wc -l
echo +ssstchlrds | sed -nE "/^.{2}s/p; /^.{5}s/p" | wc -l
echo +mmmmmmmmmmmmmmmmm | sed -nE "/^.{11}m/p; /^.{15}m/p" | wc -l
echo +kkkkkkkkkkgkkkktbkk | sed -nE "/^.{14}k/p; /^.{17}k/p" | wc -l
echo +xlxx | sed -nE "/^.{1}x/p; /^.{2}x/p" | wc -l
echo +wwcwptczwzzd | sed -nE "/^.{9}w/p; /^.{10}w/p" | wc -l
echo +ccgcccccccccccccc | sed -nE "/^.{1}c/p; /^.{3}c/p" | wc -l
echo +nhhhvh | sed -nE "/^.{4}h/p; /^.{5}h/p" | wc -l
echo +hlllfllllmltlhlldl | sed -nE "/^.{8}l/p; /^.{16}l/p" | wc -l
echo +wgwfw | sed -nE "/^.{4}w/p; /^.{5}w/p" | wc -l
echo +pjpbfrmxqgkxkbqhj | sed -nE "/^.{6}p/p; /^.{15}p/p" | wc -l
echo +llmtllnlllllllllnns | sed -nE "/^.{12}l/p; /^.{17}l/p" | wc -l
echo +zjnxzndnznklxzjlx | sed -nE "/^.{8}n/p; /^.{15}n/p" | wc -l
echo +wpsmstnkgtrmng | sed -nE "/^.{6}r/p; /^.{9}r/p" | wc -l
echo +csvhxhsgvrsrn | sed -nE "/^.{3}s/p; /^.{7}s/p" | wc -l
echo +hchhhdhkhghlhgsh | sed -nE "/^.{10}h/p; /^.{15}h/p" | wc -l
echo +mzbmtccktc | sed -nE "/^.{2}c/p; /^.{9}c/p" | wc -l
echo +xlzvxg | sed -nE "/^.{3}x/p; /^.{4}x/p" | wc -l
echo +zmkskknwkkkmkkwkgkkk | sed -nE "/^.{12}k/p; /^.{14}k/p" | wc -l
echo +vqrrrrdzpl | sed -nE "/^.{4}r/p; /^.{9}r/p" | wc -l
echo +ggvbxg | sed -nE "/^.{3}g/p; /^.{4}g/p" | wc -l
echo +xtrqrmqq | sed -nE "/^.{5}q/p; /^.{8}q/p" | wc -l
echo +zllllllllllllllwlnll | sed -nE "/^.{16}l/p; /^.{18}l/p" | wc -l
echo +zsqszss | sed -nE "/^.{6}s/p; /^.{7}s/p" | wc -l
echo +wghgpg | sed -nE "/^.{3}g/p; /^.{4}g/p" | wc -l
echo +hzzzzrz | sed -nE "/^.{1}z/p; /^.{6}z/p" | wc -l
echo +hthfqtccnq | sed -nE "/^.{3}h/p; /^.{8}h/p" | wc -l
echo +ppppppcpppppppnppppp | sed -nE "/^.{15}p/p; /^.{18}p/p" | wc -l
echo +qplkdmjntlghjlpxlq | sed -nE "/^.{3}l/p; /^.{4}l/p" | wc -l
echo +xzqkxdvgrqxqqzzxgjj | sed -nE "/^.{10}q/p; /^.{12}q/p" | wc -l
echo +qqqvsvqqxq | sed -nE "/^.{6}q/p; /^.{9}q/p" | wc -l
echo +shgcnjlgvcgqg | sed -nE "/^.{12}g/p; /^.{13}g/p" | wc -l
echo +llklplllmlsl | sed -nE "/^.{5}l/p; /^.{10}l/p" | wc -l
echo +vllqfzwnsqslpnvrbkh | sed -nE "/^.{3}l/p; /^.{12}l/p" | wc -l
echo +gjggggggggggggbzcggg | sed -nE "/^.{14}g/p; /^.{16}g/p" | wc -l
echo +ssmsmbnspmm | sed -nE "/^.{5}m/p; /^.{11}m/p" | wc -l
echo +mkqvvvvvmcvvz | sed -nE "/^.{11}v/p; /^.{13}v/p" | wc -l
echo +mkkchtzqsvkbclgxn | sed -nE "/^.{2}k/p; /^.{3}k/p" | wc -l
echo +rphrrnrrqwknrktrgsg | sed -nE "/^.{4}r/p; /^.{7}r/p" | wc -l
echo +vpjhzzzkqzjl | sed -nE "/^.{6}z/p; /^.{10}z/p" | wc -l
echo +ccccccccccccccchccc | sed -nE "/^.{16}c/p; /^.{18}c/p" | wc -l
echo +qvvvvzvvvvvv | sed -nE "/^.{1}v/p; /^.{10}v/p" | wc -l
echo +jjrjjjj | sed -nE "/^.{5}j/p; /^.{7}j/p" | wc -l
echo +zlgdrlqllgpllfhh | sed -nE "/^.{14}l/p; /^.{16}l/p" | wc -l
echo +llmllll | sed -nE "/^.{3}l/p; /^.{6}l/p" | wc -l
echo +smdl | sed -nE "/^.{3}l/p; /^.{4}l/p" | wc -l
echo +kgqhcpvrbldrhbq | sed -nE "/^.{4}h/p; /^.{11}h/p" | wc -l
echo +ljjjjjjjjjjjjjjj | sed -nE "/^.{1}j/p; /^.{15}j/p" | wc -l
echo +ccccccccccccccc | sed -nE "/^.{7}c/p; /^.{14}c/p" | wc -l
echo +vzvjvvvvvvvvv | sed -nE "/^.{2}v/p; /^.{10}v/p" | wc -l
echo +flbpmqmhkpt | sed -nE "/^.{4}p/p; /^.{9}p/p" | wc -l
echo +rtdrqmpcsqrhqqchqczw | sed -nE "/^.{10}q/p; /^.{12}q/p" | wc -l
echo +vlwxgtmjwrzvqgdwbdw | sed -nE "/^.{16}w/p; /^.{19}w/p" | wc -l
echo +gkcccslctcmszhc | sed -nE "/^.{8}c/p; /^.{15}c/p" | wc -l
echo +hhffhbbtbwzw | sed -nE "/^.{3}f/p; /^.{7}f/p" | wc -l
echo +msbsxssds | sed -nE "/^.{4}s/p; /^.{9}s/p" | wc -l
echo +pppppppppcpppxldp | sed -nE "/^.{13}p/p; /^.{15}p/p" | wc -l
echo +mmmmmqmm | sed -nE "/^.{6}m/p; /^.{7}m/p" | wc -l
echo +mxmmzwmmmdqpmp | sed -nE "/^.{11}m/p; /^.{12}m/p" | wc -l
echo +gncmgzxlqcllqgt | sed -nE "/^.{7}l/p; /^.{12}l/p" | wc -l
echo +tttttttttttdtt | sed -nE "/^.{12}t/p; /^.{14}t/p" | wc -l
echo +ffffffbrfffp | sed -nE "/^.{2}f/p; /^.{6}f/p" | wc -l
echo +hhdhpphhhhhhkhhxqph | sed -nE "/^.{14}h/p; /^.{17}h/p" | wc -l
echo +xxxxxxxxqxxxxxx | sed -nE "/^.{7}x/p; /^.{9}x/p" | wc -l
echo +vlwgjljtljtrdbxjnjwm | sed -nE "/^.{5}j/p; /^.{18}j/p" | wc -l
echo +jmncnsndnbwx | sed -nE "/^.{5}n/p; /^.{7}n/p" | wc -l
echo +rrrrrrrrr | sed -nE "/^.{8}r/p; /^.{9}r/p" | wc -l
echo +jjjjjjjjjjjjjjpjr | sed -nE "/^.{11}j/p; /^.{17}j/p" | wc -l
echo +xxxxjt | sed -nE "/^.{5}x/p; /^.{6}x/p" | wc -l
echo +nshmnjgzhmjdzvl | sed -nE "/^.{13}l/p; /^.{15}l/p" | wc -l
echo +wmsvzxsrqnnhfr | sed -nE "/^.{9}r/p; /^.{10}r/p" | wc -l
echo +kkkxxrkpktg | sed -nE "/^.{8}k/p; /^.{11}k/p" | wc -l
echo +rrrrrrrfrrrjwrd | sed -nE "/^.{1}r/p; /^.{7}r/p" | wc -l
echo +rztvtvplbrk | sed -nE "/^.{5}t/p; /^.{7}t/p" | wc -l
echo +wwwwwwsw | sed -nE "/^.{2}w/p; /^.{7}w/p" | wc -l
echo +sgggk | sed -nE "/^.{1}g/p; /^.{2}g/p" | wc -l
echo +jjjjjwjjjjvvjjjrjs | sed -nE "/^.{12}j/p; /^.{13}j/p" | wc -l
echo +cccccc | sed -nE "/^.{1}c/p; /^.{2}c/p" | wc -l
echo +khgzr | sed -nE "/^.{3}g/p; /^.{5}g/p" | wc -l
echo +bbbbbbcbsbbbbbbb | sed -nE "/^.{9}b/p; /^.{16}b/p" | wc -l
echo +zzzzzzzzzszkz | sed -nE "/^.{12}z/p; /^.{13}z/p" | wc -l
echo +rkrrrr | sed -nE "/^.{4}r/p; /^.{5}r/p" | wc -l
echo +tgbqtddbmq | sed -nE "/^.{1}t/p; /^.{2}t/p" | wc -l
echo +wkwwwww | sed -nE "/^.{1}w/p; /^.{2}w/p" | wc -l
echo +qqdqqqqqqqqhqnb | sed -nE "/^.{14}q/p; /^.{15}q/p" | wc -l
echo +rrrrrdmrr | sed -nE "/^.{6}r/p; /^.{7}r/p" | wc -l
echo +jjjjjjjqhjjjjj | sed -nE "/^.{8}j/p; /^.{9}j/p" | wc -l
echo +gwmlntffstzllvs | sed -nE "/^.{3}t/p; /^.{6}t/p" | wc -l
echo +hhhhnhhhqh | sed -nE "/^.{6}h/p; /^.{8}h/p" | wc -l
echo +cwcwwwwwgxwwbw | sed -nE "/^.{9}w/p; /^.{11}w/p" | wc -l
echo +wwwwcwwww | sed -nE "/^.{5}w/p; /^.{9}w/p" | wc -l
echo +snjmkkhrgkkzkkpskk | sed -nE "/^.{8}k/p; /^.{12}k/p" | wc -l
echo +lvqjqlq | sed -nE "/^.{3}q/p; /^.{6}q/p" | wc -l
echo +zzzn | sed -nE "/^.{3}z/p; /^.{4}z/p" | wc -l
echo +dvmvhttxtmzhrr | sed -nE "/^.{9}t/p; /^.{12}t/p" | wc -l
echo +kkkkkkskkkkkk | sed -nE "/^.{3}k/p; /^.{7}k/p" | wc -l
echo +vqvvvdvvvvbvvvvvvvvv | sed -nE "/^.{6}v/p; /^.{15}v/p" | wc -l
echo +jzzzzzdk | sed -nE "/^.{3}z/p; /^.{4}z/p" | wc -l
echo +bbbbbbbbbbbs | sed -nE "/^.{8}b/p; /^.{12}b/p" | wc -l
echo +nvhwmwgmmqkbmmmzb | sed -nE "/^.{3}m/p; /^.{9}m/p" | wc -l
echo +npwjcgwrwcrx | sed -nE "/^.{8}r/p; /^.{10}r/p" | wc -l
echo +rxdrr | sed -nE "/^.{1}r/p; /^.{5}r/p" | wc -l
echo +ppppppsbkmppkp | sed -nE "/^.{6}p/p; /^.{9}p/p" | wc -l
echo +jjjqjjjz | sed -nE "/^.{1}j/p; /^.{4}j/p" | wc -l
echo +rblbbbbbbp | sed -nE "/^.{6}b/p; /^.{7}b/p" | wc -l
echo +tttttttttf | sed -nE "/^.{5}t/p; /^.{9}t/p" | wc -l
echo +czcccccccc | sed -nE "/^.{8}c/p; /^.{9}c/p" | wc -l
echo +jjjbjjtbjjjjjj | sed -nE "/^.{13}j/p; /^.{14}j/p" | wc -l
echo +pwppzqvp | sed -nE "/^.{3}p/p; /^.{8}p/p" | wc -l
echo +mmzmmmmmmmmmmm | sed -nE "/^.{3}m/p; /^.{12}m/p" | wc -l
echo +ddjddddddqddd | sed -nE "/^.{3}d/p; /^.{9}d/p" | wc -l
echo +qqfq | sed -nE "/^.{3}q/p; /^.{4}q/p" | wc -l
echo +mmmmmbmmmmwmmlmmmm | sed -nE "/^.{6}m/p; /^.{14}m/p" | wc -l
echo +glgzc | sed -nE "/^.{3}c/p; /^.{4}c/p" | wc -l
echo +ttttttt | sed -nE "/^.{6}t/p; /^.{7}t/p" | wc -l
echo +sssbs | sed -nE "/^.{1}s/p; /^.{4}s/p" | wc -l
echo +drrkrrrzrrrr | sed -nE "/^.{5}r/p; /^.{8}r/p" | wc -l
echo +rvqfqqkllqqqlfrq | sed -nE "/^.{10}q/p; /^.{12}q/p" | wc -l
echo +szsssssssssssss | sed -nE "/^.{11}s/p; /^.{13}s/p" | wc -l
echo +tttttttsttvt | sed -nE "/^.{8}t/p; /^.{11}t/p" | wc -l
echo +zjjjjjjjjjjjjjjjjj | sed -nE "/^.{11}j/p; /^.{15}j/p" | wc -l
echo +dvfs | sed -nE "/^.{2}s/p; /^.{4}s/p" | wc -l
echo +zhpq | sed -nE "/^.{3}q/p; /^.{4}q/p" | wc -l
echo +cccccccccckc | sed -nE "/^.{10}c/p; /^.{11}c/p" | wc -l
echo +pnrjhtdlkzvhh | sed -nE "/^.{5}h/p; /^.{11}h/p" | wc -l
echo +nlllxgnrlllllllmq | sed -nE "/^.{5}l/p; /^.{9}l/p" | wc -l
echo +gfff | sed -nE "/^.{3}f/p; /^.{4}f/p" | wc -l
echo +grgggggbg | sed -nE "/^.{8}g/p; /^.{9}g/p" | wc -l
echo +pfwjhh | sed -nE "/^.{3}j/p; /^.{4}j/p" | wc -l
echo +jlfjr | sed -nE "/^.{2}l/p; /^.{5}l/p" | wc -l
echo +lblv | sed -nE "/^.{2}l/p; /^.{4}l/p" | wc -l
echo +qqvzhnqqhqvqq | sed -nE "/^.{3}q/p; /^.{10}q/p" | wc -l
echo +tfttttttktwttts | sed -nE "/^.{11}t/p; /^.{15}t/p" | wc -l
echo +gqptrzwclbdbfqd | sed -nE "/^.{12}b/p; /^.{14}b/p" | wc -l
echo +crrprr | sed -nE "/^.{1}r/p; /^.{4}r/p" | wc -l
echo +qvdvvvdnrqmrqp | sed -nE "/^.{5}v/p; /^.{13}v/p" | wc -l
echo +rwrrlsrrsrrjgdnrrr | sed -nE "/^.{9}r/p; /^.{12}r/p" | wc -l
echo +ccldccnp | sed -nE "/^.{4}c/p; /^.{6}c/p" | wc -l
echo +qqqqqpqqqqlqqqqmlq | sed -nE "/^.{16}q/p; /^.{17}q/p" | wc -l
echo +wwwwwwwhwmwws | sed -nE "/^.{2}w/p; /^.{8}w/p" | wc -l
echo +dmmbmmdmkxm | sed -nE "/^.{3}m/p; /^.{6}m/p" | wc -l
echo +xflrtblvcvfxnlf | sed -nE "/^.{6}t/p; /^.{13}t/p" | wc -l
echo +pmnsmm | sed -nE "/^.{2}m/p; /^.{6}m/p" | wc -l
echo +kstfvnkkgfvvkbk | sed -nE "/^.{13}k/p; /^.{15}k/p" | wc -l
echo +jqwcwlcwcwvqbfzfzfm | sed -nE "/^.{4}w/p; /^.{10}w/p" | wc -l
echo +ddndbmjxhfqqn | sed -nE "/^.{1}d/p; /^.{5}d/p" | wc -l
echo +pzvbszhqtpklpkpdw | sed -nE "/^.{13}p/p; /^.{16}p/p" | wc -l
echo +thttwmxjsbtp | sed -nE "/^.{2}t/p; /^.{4}t/p" | wc -l
echo +zbsvjcssfmf | sed -nE "/^.{8}s/p; /^.{10}s/p" | wc -l
echo +lltlwlllll | sed -nE "/^.{3}l/p; /^.{5}l/p" | wc -l
echo +hgfvvfpnrvpfggnss | sed -nE "/^.{12}g/p; /^.{14}g/p" | wc -l
echo +cjmbvgxchmqdqcvc | sed -nE "/^.{3}q/p; /^.{13}q/p" | wc -l
echo +cjjjjjjjjjjqjjjjjj | sed -nE "/^.{12}j/p; /^.{16}j/p" | wc -l
echo +kqrgm | sed -nE "/^.{1}m/p; /^.{5}m/p" | wc -l
echo +xcjpwbrrffxkfxh | sed -nE "/^.{11}x/p; /^.{14}x/p" | wc -l
echo +kgfnccxqczkcjkcc | sed -nE "/^.{12}c/p; /^.{14}c/p" | wc -l
echo +sfftf | sed -nE "/^.{3}f/p; /^.{4}f/p" | wc -l
echo +ffdz | sed -nE "/^.{1}f/p; /^.{3}f/p" | wc -l
echo +xftfxmkttdsttg | sed -nE "/^.{12}t/p; /^.{14}t/p" | wc -l
echo +ffhcgfffffff | sed -nE "/^.{4}f/p; /^.{9}f/p" | wc -l
echo +zjlbbsbzbx | sed -nE "/^.{9}b/p; /^.{10}b/p" | wc -l
echo +hhxmlmmmzmmtmm | sed -nE "/^.{9}m/p; /^.{14}m/p" | wc -l
echo +tkcpzjwr | sed -nE "/^.{3}t/p; /^.{5}t/p" | wc -l
echo +wkfdwflgrntrknsr | sed -nE "/^.{6}k/p; /^.{9}k/p" | wc -l
echo +gfml | sed -nE "/^.{1}l/p; /^.{4}l/p" | wc -l
echo +zzzzzzzzzrzzzz | sed -nE "/^.{9}z/p; /^.{10}z/p" | wc -l
echo +hhhhhhhhhhzhh | sed -nE "/^.{9}h/p; /^.{11}h/p" | wc -l
echo +kkkkkkkkzkkkkkkk | sed -nE "/^.{1}k/p; /^.{9}k/p" | wc -l
echo +sswmmkhkvhw | sed -nE "/^.{2}h/p; /^.{7}h/p" | wc -l
echo +pmbnnmzrkk | sed -nE "/^.{2}m/p; /^.{5}m/p" | wc -l
echo +xhpfbfdffkfw | sed -nE "/^.{9}f/p; /^.{12}f/p" | wc -l
echo +gfwg | sed -nE "/^.{3}g/p; /^.{4}g/p" | wc -l
echo +nnnnnnnnnnnpnnnxn | sed -nE "/^.{11}n/p; /^.{12}n/p" | wc -l
echo +dddddgddd | sed -nE "/^.{5}d/p; /^.{6}d/p" | wc -l
echo +cbjgnjqjgj | sed -nE "/^.{7}j/p; /^.{9}j/p" | wc -l
echo +rrrrrrrhrrrrrzbrr | sed -nE "/^.{9}r/p; /^.{14}r/p" | wc -l
echo +prphk | sed -nE "/^.{4}p/p; /^.{5}p/p" | wc -l
echo +dpdd | sed -nE "/^.{2}d/p; /^.{4}d/p" | wc -l
echo +zjsppzhqqgqspcppqpps | sed -nE "/^.{5}p/p; /^.{15}p/p" | wc -l
echo +rrrrrrfwrr | sed -nE "/^.{2}r/p; /^.{7}r/p" | wc -l
echo +hhqh | sed -nE "/^.{1}h/p; /^.{3}h/p" | wc -l
echo +zgvdgspkjrrvcgdlxg | sed -nE "/^.{14}g/p; /^.{16}g/p" | wc -l
echo +psgqccccvc | sed -nE "/^.{4}c/p; /^.{6}c/p" | wc -l
echo +qdqjqmttdtcqggqpqn | sed -nE "/^.{9}q/p; /^.{14}q/p" | wc -l
echo +ffffffffffffgffffff | sed -nE "/^.{13}f/p; /^.{18}f/p" | wc -l
echo +gggggggggggg | sed -nE "/^.{8}g/p; /^.{9}g/p" | wc -l
echo +xxxxxxxxxxxr | sed -nE "/^.{11}x/p; /^.{12}x/p" | wc -l
echo +cxcccfchcccccccbbcm | sed -nE "/^.{2}c/p; /^.{17}c/p" | wc -l
echo +nwbrzndvrfxwt | sed -nE "/^.{7}b/p; /^.{11}b/p" | wc -l
echo +xhwxxxv | sed -nE "/^.{3}x/p; /^.{4}x/p" | wc -l
echo +rzrrnrrrvxrrzrrrrrr | sed -nE "/^.{16}r/p; /^.{17}r/p" | wc -l
echo +zcvgbmxvwp | sed -nE "/^.{2}f/p; /^.{3}f/p" | wc -l
echo +fwbbbf | sed -nE "/^.{5}b/p; /^.{6}b/p" | wc -l
echo +mmmmmpmmmw | sed -nE "/^.{6}m/p; /^.{10}m/p" | wc -l
echo +bnnvndbpvzj | sed -nE "/^.{2}n/p; /^.{4}n/p" | wc -l
echo +dftfhdngqp | sed -nE "/^.{3}t/p; /^.{4}t/p" | wc -l
echo +vtvvvvvvvvv | sed -nE "/^.{1}v/p; /^.{2}v/p" | wc -l
echo +vgvv | sed -nE "/^.{2}v/p; /^.{3}v/p" | wc -l
echo +tsvsshsssgssssmsksss | sed -nE "/^.{9}s/p; /^.{10}s/p" | wc -l
echo +ttttttxt | sed -nE "/^.{6}t/p; /^.{7}t/p" | wc -l
echo +jcrc | sed -nE "/^.{3}c/p; /^.{4}c/p" | wc -l
echo +ztlmjljlb | sed -nE "/^.{5}l/p; /^.{8}l/p" | wc -l
echo +bwwwww | sed -nE "/^.{4}w/p; /^.{5}w/p" | wc -l
echo +rrrbrrrrrrnrrrs | sed -nE "/^.{11}r/p; /^.{14}r/p" | wc -l
echo +zzzzznzzzwzzzzzzzz | sed -nE "/^.{10}z/p; /^.{16}z/p" | wc -l
echo +mmmmmmfmmmmmmmmmmmmm | sed -nE "/^.{7}m/p; /^.{13}m/p" | wc -l
echo +fflzcwftmcswcwwnwts | sed -nE "/^.{15}w/p; /^.{19}w/p" | wc -l
echo +bjbbbbbbmwbbbbbbbbtb | sed -nE "/^.{10}b/p; /^.{19}b/p" | wc -l
echo +xxxxpxxpxxqxdqxxxx | sed -nE "/^.{14}x/p; /^.{16}x/p" | wc -l
echo +rkzrjbxrgwkhnb | sed -nE "/^.{8}r/p; /^.{13}r/p" | wc -l
echo +rrrzfkrrrrrrrrtrrnrr | sed -nE "/^.{5}r/p; /^.{18}r/p" | wc -l
echo +bbbfzb | sed -nE "/^.{4}b/p; /^.{5}b/p" | wc -l
echo +qnscxqqfqb | sed -nE "/^.{6}q/p; /^.{10}q/p" | wc -l
echo +wwwwwwwfwwwwwwwwww | sed -nE "/^.{8}w/p; /^.{13}w/p" | wc -l
echo +scvnsnpgnjnmdpnwct | sed -nE "/^.{10}n/p; /^.{11}n/p" | wc -l
echo +pjpppppdqpjpfppsptp | sed -nE "/^.{7}p/p; /^.{11}p/p" | wc -l
echo +jfsvclhfm | sed -nE "/^.{7}n/p; /^.{9}n/p" | wc -l
echo +whsggqscd | sed -nE "/^.{3}h/p; /^.{8}h/p" | wc -l
echo +mrmpxhrqsdmqpjshvck | sed -nE "/^.{2}r/p; /^.{12}r/p" | wc -l
echo +gdgggg | sed -nE "/^.{2}g/p; /^.{4}g/p" | wc -l
echo +ssssssssgsss | sed -nE "/^.{7}s/p; /^.{12}s/p" | wc -l
echo +dlklllnjlslbl | sed -nE "/^.{7}l/p; /^.{11}l/p" | wc -l
echo +kkkkkkkkkkkkkkk | sed -nE "/^.{5}k/p; /^.{11}k/p" | wc -l
echo +dhtvcgmfrjhk | sed -nE "/^.{6}g/p; /^.{9}g/p" | wc -l
echo +lmmmhmsmmmmmcmmmmzmm | sed -nE "/^.{4}m/p; /^.{5}m/p" | wc -l
echo +zgtnkjzmtkttmtkc | sed -nE "/^.{11}t/p; /^.{13}t/p" | wc -l
echo +bbbbbbv | sed -nE "/^.{6}b/p; /^.{7}b/p" | wc -l
echo +qqcq | sed -nE "/^.{3}q/p; /^.{4}q/p" | wc -l
echo +zzzszjzszzczmxtzzcl | sed -nE "/^.{12}z/p; /^.{16}z/p" | wc -l
echo +wwfhp | sed -nE "/^.{2}w/p; /^.{5}w/p" | wc -l
echo +gddkd | sed -nE "/^.{1}d/p; /^.{2}d/p" | wc -l
echo +fwqgbvrcfmwb | sed -nE "/^.{5}f/p; /^.{12}f/p" | wc -l
echo +bnxcw | sed -nE "/^.{2}w/p; /^.{5}w/p" | wc -l
echo +ncwftppphsxvztttjs | sed -nE "/^.{3}t/p; /^.{15}t/p" | wc -l
echo +ppnsppkcppsp | sed -nE "/^.{7}p/p; /^.{10}p/p" | wc -l
echo +vvrdvv | sed -nE "/^.{5}v/p; /^.{6}v/p" | wc -l
echo +hczwbzz | sed -nE "/^.{5}z/p; /^.{6}z/p" | wc -l
echo +gcphfgmzfkflspmxg | sed -nE "/^.{3}p/p; /^.{12}p/p" | wc -l
echo +jmfmfjpvbmfmmrdkdnzp | sed -nE "/^.{14}m/p; /^.{19}m/p" | wc -l
echo +pdwzppppp | sed -nE "/^.{6}p/p; /^.{7}p/p" | wc -l
echo +bbbnbbqbb | sed -nE "/^.{4}b/p; /^.{7}b/p" | wc -l
echo +frrrrrxxr | sed -nE "/^.{7}r/p; /^.{8}r/p" | wc -l
echo +jbphpzgvnppwhkxfzs | sed -nE "/^.{8}b/p; /^.{18}b/p" | wc -l
echo +pvhcc | sed -nE "/^.{1}c/p; /^.{5}c/p" | wc -l
echo +fzznzjzztstzxrz | sed -nE "/^.{4}z/p; /^.{8}z/p" | wc -l
echo +jvvwvvvlvlvqc | sed -nE "/^.{5}v/p; /^.{10}v/p" | wc -l
echo +svgrzfpxkdpbhph | sed -nE "/^.{7}p/p; /^.{14}p/p" | wc -l
echo +nncmvkn | sed -nE "/^.{5}n/p; /^.{7}n/p" | wc -l
echo +rrlrbrrrvrrr | sed -nE "/^.{11}r/p; /^.{12}r/p" | wc -l
echo +vtngrndhqf | sed -nE "/^.{1}r/p; /^.{5}r/p" | wc -l
echo +knjp | sed -nE "/^.{2}k/p; /^.{4}k/p" | wc -l
echo +hhghhhhhhhxhhwhhh | sed -nE "/^.{11}h/p; /^.{14}h/p" | wc -l
echo +rrrrrrrrrrrrrrrpnb | sed -nE "/^.{16}r/p; /^.{18}r/p" | wc -l
echo +dpddbvdtdmxfdddd | sed -nE "/^.{10}d/p; /^.{14}d/p" | wc -l
echo +cztt | sed -nE "/^.{2}t/p; /^.{4}t/p" | wc -l
echo +rzrprd | sed -nE "/^.{5}r/p; /^.{6}r/p" | wc -l
echo +ngwdngc | sed -nE "/^.{2}n/p; /^.{5}n/p" | wc -l
echo +qqqzzwwqqqkqqq | sed -nE "/^.{1}q/p; /^.{6}q/p" | wc -l
echo +lllzllpxl | sed -nE "/^.{7}l/p; /^.{8}l/p" | wc -l
echo +kmltzzjzbppgwq | sed -nE "/^.{1}b/p; /^.{4}b/p" | wc -l
echo +ttttb | sed -nE "/^.{1}t/p; /^.{4}t/p" | wc -l
echo +dkxpcph | sed -nE "/^.{3}p/p; /^.{4}p/p" | wc -l
echo +zzzzzzhzzzzzzzzzz | sed -nE "/^.{7}z/p; /^.{15}z/p" | wc -l
echo +cdljfccm | sed -nE "/^.{4}c/p; /^.{7}c/p" | wc -l
echo +hbpxhlmc | sed -nE "/^.{3}p/p; /^.{8}p/p" | wc -l
echo +wwwlw | sed -nE "/^.{4}w/p; /^.{5}w/p" | wc -l
echo +lbqbbbkgbbwfbdb | sed -nE "/^.{14}b/p; /^.{15}b/p" | wc -l
echo +jtjjvpwwthwcsj | sed -nE "/^.{6}j/p; /^.{10}j/p" | wc -l
echo +ltvtttbtqxtzq | sed -nE "/^.{5}t/p; /^.{8}t/p" | wc -l
echo +ttttttttjttztxt | sed -nE "/^.{12}t/p; /^.{13}t/p" | wc -l
echo +ppppppppppppppxpxbpp | sed -nE "/^.{16}p/p; /^.{18}p/p" | wc -l
echo +nnnrnnnnt | sed -nE "/^.{4}n/p; /^.{7}n/p" | wc -l
echo +rfrr | sed -nE "/^.{1}r/p; /^.{2}r/p" | wc -l
echo +ggggvggg | sed -nE "/^.{5}g/p; /^.{6}g/p" | wc -l
echo +ssbw | sed -nE "/^.{3}s/p; /^.{4}s/p" | wc -l
echo +ldll | sed -nE "/^.{3}l/p; /^.{4}l/p" | wc -l
echo +mmmmvmmcjkmg | sed -nE "/^.{8}m/p; /^.{10}m/p" | wc -l
echo +wwvwwvwwhwwjwwwlwxcm | sed -nE "/^.{10}w/p; /^.{18}w/p" | wc -l
echo +cxxxxxxxxxxxxx | sed -nE "/^.{1}x/p; /^.{2}x/p" | wc -l
echo +bbbbkbbb | sed -nE "/^.{1}b/p; /^.{5}b/p" | wc -l
echo +zwqzrrzzvqqzzszrx | sed -nE "/^.{12}z/p; /^.{14}z/p" | wc -l
echo +lzzfzzzfz | sed -nE "/^.{1}z/p; /^.{5}z/p" | wc -l
echo +ftgstrgptwmptxrzt | sed -nE "/^.{16}t/p; /^.{17}t/p" | wc -l
echo +bbbbbbbzbbbb | sed -nE "/^.{9}b/p; /^.{10}b/p" | wc -l
echo +wwwwwwwjwwwzwzww | sed -nE "/^.{8}w/p; /^.{14}w/p" | wc -l
echo +qhnh | sed -nE "/^.{3}h/p; /^.{4}h/p" | wc -l
echo +dnddddkddddzdxdddd | sed -nE "/^.{2}d/p; /^.{12}d/p" | wc -l
echo +xxxxxxxxxxxxxxxxx | sed -nE "/^.{5}x/p; /^.{17}x/p" | wc -l
echo +hhhhtqhhhrh | sed -nE "/^.{9}h/p; /^.{10}h/p" | wc -l
echo +pfmppppp | sed -nE "/^.{6}p/p; /^.{7}p/p" | wc -l
echo +vbvvvvvs | sed -nE "/^.{5}v/p; /^.{8}v/p" | wc -l
echo +qhfhqcb | sed -nE "/^.{4}h/p; /^.{5}h/p" | wc -l
echo +dlddlhhwvcrdrxwpt | sed -nE "/^.{3}d/p; /^.{12}d/p" | wc -l
echo +nnwnp | sed -nE "/^.{2}n/p; /^.{3}n/p" | wc -l
echo +ggggjgfgzgdglgg | sed -nE "/^.{4}g/p; /^.{8}g/p" | wc -l
echo +vrghsphxhxzsxw | sed -nE "/^.{4}h/p; /^.{9}h/p" | wc -l
echo +qrzzzfwdcwnzdzkckz | sed -nE "/^.{12}z/p; /^.{18}z/p" | wc -l
echo +zvmlqwwh | sed -nE "/^.{6}v/p; /^.{8}v/p" | wc -l
echo +pppxwpndfpwppdpptmpp | sed -nE "/^.{10}p/p; /^.{14}p/p" | wc -l
echo +qqnqkqkqjgrcqfq | sed -nE "/^.{12}q/p; /^.{15}q/p" | wc -l
echo +pnszjnnn | sed -nE "/^.{2}n/p; /^.{4}n/p" | wc -l
echo +zkctcfc | sed -nE "/^.{2}c/p; /^.{3}c/p" | wc -l
echo +lvjlcclllslzllllwgll | sed -nE "/^.{17}l/p; /^.{20}l/p" | wc -l
echo +dfgskkfkkkfjhfvfks | sed -nE "/^.{16}k/p; /^.{17}k/p" | wc -l
echo +tjttltt | sed -nE "/^.{1}t/p; /^.{3}t/p" | wc -l
echo +bbzbb | sed -nE "/^.{2}b/p; /^.{3}b/p" | wc -l
echo +dtttttsttlttttzlttj | sed -nE "/^.{8}t/p; /^.{15}t/p" | wc -l
echo +vvkvvjvgwvvvkvf | sed -nE "/^.{13}v/p; /^.{14}v/p" | wc -l
echo +tvvvvvvhv | sed -nE "/^.{7}v/p; /^.{8}v/p" | wc -l
echo +bxktdrtddtdtsh | sed -nE "/^.{3}d/p; /^.{10}d/p" | wc -l
echo +npwxjjjjbjkq | sed -nE "/^.{4}j/p; /^.{12}j/p" | wc -l
echo +tlllll | sed -nE "/^.{1}l/p; /^.{4}l/p" | wc -l
echo +lbhpxbbbvbbbqbbbsbb | sed -nE "/^.{12}b/p; /^.{13}b/p" | wc -l
echo +vqhsggmpvmqtbzzlq | sed -nE "/^.{9}v/p; /^.{15}v/p" | wc -l
echo +ffhfjfffqfxqff | sed -nE "/^.{12}f/p; /^.{14}f/p" | wc -l
echo +jtnsjwpggbpxlhqmk | sed -nE "/^.{15}m/p; /^.{16}m/p" | wc -l
echo +xptncjsstcl | sed -nE "/^.{2}n/p; /^.{4}n/p" | wc -l
echo +dmwklqjqnzb | sed -nE "/^.{5}q/p; /^.{8}q/p" | wc -l
echo +vcgl | sed -nE "/^.{3}c/p; /^.{4}c/p" | wc -l
echo +hhhhhh | sed -nE "/^.{1}h/p; /^.{6}h/p" | wc -l
echo +ckblstcdx | sed -nE "/^.{8}x/p; /^.{9}x/p" | wc -l
echo +vwphwwmwwwww | sed -nE "/^.{5}w/p; /^.{7}w/p" | wc -l
echo +kxxxdh | sed -nE "/^.{2}x/p; /^.{4}x/p" | wc -l
echo +kmmvmmmfmksmj | sed -nE "/^.{10}m/p; /^.{11}m/p" | wc -l
echo +zvrvvvdvvv | sed -nE "/^.{4}v/p; /^.{7}v/p" | wc -l
echo +npxbwqpxbjrnrv | sed -nE "/^.{1}p/p; /^.{8}p/p" | wc -l
echo +jfkwttkstrxlgts | sed -nE "/^.{5}t/p; /^.{11}t/p" | wc -l
echo +ggggg | sed -nE "/^.{1}g/p; /^.{2}g/p" | wc -l
echo +tpppppr | sed -nE "/^.{5}p/p; /^.{7}p/p" | wc -l
echo +vvvvvvvvvvvvvvvvvvvv | sed -nE "/^.{15}v/p; /^.{17}v/p" | wc -l
echo +dwjwjznczwgfmkmhdtw | sed -nE "/^.{17}w/p; /^.{19}w/p" | wc -l
echo +fffffbqfffffffffff | sed -nE "/^.{10}f/p; /^.{13}f/p" | wc -l
echo +ggggggggggggggg | sed -nE "/^.{4}g/p; /^.{14}g/p" | wc -l
echo +bdkfd | sed -nE "/^.{2}d/p; /^.{3}d/p" | wc -l
echo +xxxxxxxx | sed -nE "/^.{7}x/p; /^.{8}x/p" | wc -l
echo +hmshdhvvhkhbhcshs | sed -nE "/^.{6}h/p; /^.{9}h/p" | wc -l
echo +gggggggggggggghg | sed -nE "/^.{14}g/p; /^.{15}g/p" | wc -l
echo +qqsxqqqdgqqghqqk | sed -nE "/^.{2}q/p; /^.{16}q/p" | wc -l
echo +ppbppprppppppppphppp | sed -nE "/^.{3}p/p; /^.{17}p/p" | wc -l
echo +vczfvqcvvcspndvxwjdv | sed -nE "/^.{8}v/p; /^.{18}v/p" | wc -l
echo +fdddd | sed -nE "/^.{1}d/p; /^.{3}d/p" | wc -l
echo +gfjjnjsdnhb | sed -nE "/^.{9}j/p; /^.{11}j/p" | wc -l
echo +hkhshttssl | sed -nE "/^.{8}s/p; /^.{10}s/p" | wc -l
echo +ffsffffffqxfff | sed -nE "/^.{5}f/p; /^.{10}f/p" | wc -l
echo +wwlwwckwwf | sed -nE "/^.{7}w/p; /^.{10}w/p" | wc -l
echo +blxxmtbgnblfgnfwz | sed -nE "/^.{4}x/p; /^.{8}x/p" | wc -l
echo +rlpkprppp | sed -nE "/^.{4}p/p; /^.{5}p/p" | wc -l
echo +ssssssssssssswss | sed -nE "/^.{13}s/p; /^.{14}s/p" | wc -l
echo +hhhdhmhhhjhlhh | sed -nE "/^.{4}h/p; /^.{8}h/p" | wc -l
echo +chhhhhfhzqhdhhh | sed -nE "/^.{6}h/p; /^.{7}h/p" | wc -l
echo +msvrmwzkzvmmgrmmpm | sed -nE "/^.{15}m/p; /^.{17}m/p" | wc -l
echo +qgtwwxhgsxxmklgmn | sed -nE "/^.{4}x/p; /^.{6}x/p" | wc -l
echo +rpzkdpp | sed -nE "/^.{4}p/p; /^.{7}p/p" | wc -l
echo +vvvhvjv | sed -nE "/^.{3}v/p; /^.{4}v/p" | wc -l
echo +pppppppppppppppppmp | sed -nE "/^.{16}p/p; /^.{18}p/p" | wc -l
echo +kpkkkkkhqkkkkklktk | sed -nE "/^.{15}k/p; /^.{17}k/p" | wc -l
echo +ssbxxsk | sed -nE "/^.{5}s/p; /^.{7}s/p" | wc -l
echo +cwllll | sed -nE "/^.{2}l/p; /^.{4}l/p" | wc -l
echo +cvvrrkvrvsdvfwcv | sed -nE "/^.{6}v/p; /^.{9}v/p" | wc -l
echo +qwwwwslwwwwwwwwrww | sed -nE "/^.{1}w/p; /^.{7}w/p" | wc -l
echo +clcccccccccccccc | sed -nE "/^.{2}c/p; /^.{12}c/p" | wc -l
echo +ftcmrpmvrzc | sed -nE "/^.{5}m/p; /^.{10}m/p" | wc -l
echo +wwwwwwwwwwtwwwww | sed -nE "/^.{7}w/p; /^.{11}w/p" | wc -l
echo +jngdlvgcvtkmn | sed -nE "/^.{2}n/p; /^.{3}n/p" | wc -l
echo +hvvvvvvvvv | sed -nE "/^.{1}v/p; /^.{8}v/p" | wc -l
echo +jrpvltxlcqgpfxwsj | sed -nE "/^.{3}p/p; /^.{17}p/p" | wc -l
echo +kkkkfkk | sed -nE "/^.{1}k/p; /^.{5}k/p" | wc -l
echo +cccccccccfc | sed -nE "/^.{1}c/p; /^.{10}c/p" | wc -l
echo +flfffffxfvffffprfmcb | sed -nE "/^.{13}f/p; /^.{19}f/p" | wc -l
echo +htglsbvrzcghjmd | sed -nE "/^.{3}g/p; /^.{6}g/p" | wc -l
echo +wrwghhhhnzhxl | sed -nE "/^.{9}h/p; /^.{11}h/p" | wc -l
echo +zzkzzhnjpmkvzzzw | sed -nE "/^.{5}z/p; /^.{12}z/p" | wc -l
echo +qrwcwwstwddw | sed -nE "/^.{7}w/p; /^.{11}w/p" | wc -l
echo +mmmmmmmmmmmmmmmmmmmm | sed -nE "/^.{15}m/p; /^.{19}m/p" | wc -l
echo +mmmmmmmmmmmmmmhmm | sed -nE "/^.{15}m/p; /^.{16}m/p" | wc -l
echo +xxxxxcxxxxxlxxxxxxx | sed -nE "/^.{12}x/p; /^.{16}x/p" | wc -l
echo +qwfqlllgsdjrlspll | sed -nE "/^.{5}l/p; /^.{10}l/p" | wc -l
echo +hffmfffg | sed -nE "/^.{3}f/p; /^.{4}f/p" | wc -l
echo +lwlllbllnl | sed -nE "/^.{6}l/p; /^.{7}l/p" | wc -l
echo +tttkrtlpttwftmwttttt | sed -nE "/^.{11}t/p; /^.{20}t/p" | wc -l
echo +ddbdddddddpktdd | sed -nE "/^.{11}d/p; /^.{12}d/p" | wc -l
echo +sxkmkwdwwnlwxmdvfx | sed -nE "/^.{4}w/p; /^.{11}w/p" | wc -l
echo +kkzkpk | sed -nE "/^.{4}k/p; /^.{5}k/p" | wc -l
echo +nnnnnntnnnnnbnnnbnnn | sed -nE "/^.{13}n/p; /^.{20}n/p" | wc -l
echo +ccccwcc | sed -nE "/^.{5}c/p; /^.{7}c/p" | wc -l
echo +cckkhhdhhwmhhmzchhwx | sed -nE "/^.{1}h/p; /^.{6}h/p" | wc -l
echo +hbbbbbbbbhbbhbbbbnbb | sed -nE "/^.{1}b/p; /^.{15}b/p" | wc -l
echo +mwwww | sed -nE "/^.{1}w/p; /^.{2}w/p" | wc -l
echo +sfzgwtf | sed -nE "/^.{1}f/p; /^.{2}f/p" | wc -l
echo +sssj | sed -nE "/^.{3}s/p; /^.{4}s/p" | wc -l
echo +xwww | sed -nE "/^.{1}w/p; /^.{3}w/p" | wc -l
echo +ppppppppdppppppp | sed -nE "/^.{1}p/p; /^.{16}p/p" | wc -l
echo +ccxmccccc | sed -nE "/^.{1}c/p; /^.{6}c/p" | wc -l
echo +rtpbcfbr | sed -nE "/^.{4}b/p; /^.{8}b/p" | wc -l
echo +sszssstshss | sed -nE "/^.{9}s/p; /^.{10}s/p" | wc -l
echo +xxxtxxxxxxxmxxxzx | sed -nE "/^.{15}x/p; /^.{16}x/p" | wc -l
echo +kkkkkkkkkkgrkkkkk | sed -nE "/^.{9}k/p; /^.{15}k/p" | wc -l
echo +xtxxxxxxxxrxkxx | sed -nE "/^.{11}x/p; /^.{13}x/p" | wc -l
echo +rffflfffnf | sed -nE "/^.{1}f/p; /^.{5}f/p" | wc -l
echo +nnxnnnnnnnnnbnzbnnn | sed -nE "/^.{14}n/p; /^.{16}n/p" | wc -l
echo +ddddddndbdfdhd | sed -nE "/^.{3}d/p; /^.{6}d/p" | wc -l
echo +sbqqhvqqqvqgxfq | sed -nE "/^.{14}q/p; /^.{15}q/p" | wc -l
echo +jglbfjb | sed -nE "/^.{5}b/p; /^.{6}b/p" | wc -l
echo +llllllcllsll | sed -nE "/^.{1}l/p; /^.{10}l/p" | wc -l
echo +lwzzz | sed -nE "/^.{3}z/p; /^.{5}z/p" | wc -l
echo +kkkkmkkkkkkkkkkl | sed -nE "/^.{5}k/p; /^.{12}k/p" | wc -l
echo +vvtsvfvnzvhpm | sed -nE "/^.{8}v/p; /^.{12}v/p" | wc -l
echo +llllllll | sed -nE "/^.{5}l/p; /^.{7}l/p" | wc -l
echo +nqfffkbdf | sed -nE "/^.{4}f/p; /^.{7}f/p" | wc -l
echo +jjjljkhj | sed -nE "/^.{4}j/p; /^.{8}j/p" | wc -l
echo +vgzpgfhfhmwdhbqc | sed -nE "/^.{9}h/p; /^.{15}h/p" | wc -l
echo +ptpsjqpnp | sed -nE "/^.{1}p/p; /^.{5}p/p" | wc -l
echo +qbqqwqnq | sed -nE "/^.{5}q/p; /^.{8}q/p" | wc -l
echo +wwswwxsb | sed -nE "/^.{5}w/p; /^.{7}w/p" | wc -l
echo +nnhrnhkmxqkt | sed -nE "/^.{3}h/p; /^.{6}h/p" | wc -l
echo +jwwww | sed -nE "/^.{1}w/p; /^.{3}w/p" | wc -l
echo +cxxxxdxxxxxxxbxx | sed -nE "/^.{2}x/p; /^.{14}x/p" | wc -l
echo +xxxfxxxxqxxrxt | sed -nE "/^.{12}x/p; /^.{14}x/p" | wc -l
echo +fffkffbsfkxv | sed -nE "/^.{4}f/p; /^.{9}f/p" | wc -l
echo +mmmmmmmmmmmwm | sed -nE "/^.{12}m/p; /^.{13}m/p" | wc -l
echo +ppppphpppxppp | sed -nE "/^.{6}p/p; /^.{10}p/p" | wc -l
echo +vsvvvvkmjvvvn | sed -nE "/^.{9}v/p; /^.{12}v/p" | wc -l
echo +shngvhbmjrpr | sed -nE "/^.{3}r/p; /^.{12}r/p" | wc -l
echo +wqwcwxclwwwfw | sed -nE "/^.{12}w/p; /^.{13}w/p" | wc -l
echo +nnrrdz | sed -nE "/^.{4}r/p; /^.{5}r/p" | wc -l
echo +vbcpwzvxssccqkqgmxvj | sed -nE "/^.{4}c/p; /^.{19}c/p" | wc -l
echo +tglxhggng | sed -nE "/^.{1}g/p; /^.{6}g/p" | wc -l
echo +lvzhvtglzf | sed -nE "/^.{9}z/p; /^.{10}z/p" | wc -l
echo +gddxfftggfbmxwts | sed -nE "/^.{10}f/p; /^.{16}f/p" | wc -l
echo +kkkklkkkkkkpkkk | sed -nE "/^.{4}k/p; /^.{12}k/p" | wc -l
echo +mmmmmmmmmmtm | sed -nE "/^.{7}m/p; /^.{11}m/p" | wc -l
echo +vkfpjrrvlwlbjwk | sed -nE "/^.{2}z/p; /^.{10}z/p" | wc -l
echo +dtdzwjqgxdwjhchwwd | sed -nE "/^.{3}w/p; /^.{7}w/p" | wc -l
echo +vvvvvvvvvvvvvvvv | sed -nE "/^.{13}v/p; /^.{14}v/p" | wc -l
echo +cjccccqccccc | sed -nE "/^.{11}c/p; /^.{12}c/p" | wc -l
echo +hzhrhkhfthrhxht | sed -nE "/^.{14}h/p; /^.{15}h/p" | wc -l
echo +dtwvvvvvcvvvrvsvvv | sed -nE "/^.{3}v/p; /^.{5}v/p" | wc -l
echo +qhqqkqcqqqqqlfqgsqq | sed -nE "/^.{10}q/p; /^.{14}q/p" | wc -l
echo +ffvffffffffzffffff | sed -nE "/^.{3}f/p; /^.{14}f/p" | wc -l
echo +xxtxjxzxxxxxlxxxxxxx | sed -nE "/^.{1}x/p; /^.{12}x/p" | wc -l
echo +pgpc | sed -nE "/^.{2}c/p; /^.{4}c/p" | wc -l
echo +fdrr | sed -nE "/^.{1}r/p; /^.{4}r/p" | wc -l
echo +rrrrrrt | sed -nE "/^.{5}r/p; /^.{7}r/p" | wc -l
echo +drdddddddmddddpd | sed -nE "/^.{10}d/p; /^.{11}d/p" | wc -l
echo +gfrlctftzr | sed -nE "/^.{2}f/p; /^.{5}f/p" | wc -l
echo +nrzjjrzjzzplzmzzbn | sed -nE "/^.{10}z/p; /^.{13}z/p" | wc -l
echo +cccccccgbc | sed -nE "/^.{8}c/p; /^.{10}c/p" | wc -l
echo +fgggcndwgggbjnfgb | sed -nE "/^.{5}g/p; /^.{8}g/p" | wc -l
echo +ddddghdgbddm | sed -nE "/^.{6}d/p; /^.{9}d/p" | wc -l
echo +ftjjjvjqcp | sed -nE "/^.{3}j/p; /^.{7}j/p" | wc -l
echo +sqvfstz | sed -nE "/^.{5}s/p; /^.{6}s/p" | wc -l
echo +kkkwkkkkkkbkkkkkkkbk | sed -nE "/^.{5}k/p; /^.{18}k/p" | wc -l
echo +djffffkff | sed -nE "/^.{3}f/p; /^.{6}f/p" | wc -l
echo +pqppppr | sed -nE "/^.{4}p/p; /^.{6}p/p" | wc -l
echo +hhkhjhmgcqvfhqvhn | sed -nE "/^.{5}h/p; /^.{9}h/p" | wc -l
echo +tttttttvttttt | sed -nE "/^.{8}t/p; /^.{12}t/p" | wc -l
echo +pzrzhjqmtbcnzdzr | sed -nE "/^.{14}z/p; /^.{15}z/p" | wc -l
echo +ssssssssssssswsss | sed -nE "/^.{1}s/p; /^.{17}s/p" | wc -l
echo +ssqh | sed -nE "/^.{1}s/p; /^.{4}s/p" | wc -l
echo +rrrrrrr | sed -nE "/^.{1}r/p; /^.{5}r/p" | wc -l
echo +hhhhhrhcxhhhhhhhhb | sed -nE "/^.{17}h/p; /^.{18}h/p" | wc -l
echo +dttttjmtv | sed -nE "/^.{7}t/p; /^.{9}t/p" | wc -l
echo +mcccp | sed -nE "/^.{1}c/p; /^.{3}c/p" | wc -l
echo +xprbxql | sed -nE "/^.{4}x/p; /^.{5}x/p" | wc -l
echo +cqqqqqq | sed -nE "/^.{1}q/p; /^.{5}q/p" | wc -l
echo +ggggw | sed -nE "/^.{3}g/p; /^.{4}g/p" | wc -l
echo +ffffffnf | sed -nE "/^.{1}f/p; /^.{7}f/p" | wc -l
echo +ttttttttttt | sed -nE "/^.{7}t/p; /^.{9}t/p" | wc -l
echo +mmlmfmmmmmmmmmmqm | sed -nE "/^.{11}m/p; /^.{15}m/p" | wc -l
echo +npnnnn | sed -nE "/^.{4}n/p; /^.{5}n/p" | wc -l
echo +zvbbvbjhlkf | sed -nE "/^.{4}b/p; /^.{5}b/p" | wc -l
echo +gnqmcvtzwpcbvncwcc | sed -nE "/^.{11}c/p; /^.{16}c/p" | wc -l
echo +qbqkwqqvqwqqnljsqpqt | sed -nE "/^.{12}q/p; /^.{18}q/p" | wc -l
echo +wcrtdrlkgjr | sed -nE "/^.{6}r/p; /^.{10}r/p" | wc -l
echo +gppppppppwvlgpptp | sed -nE "/^.{16}p/p; /^.{17}p/p" | wc -l
echo +gqghbwqqzwwdk | sed -nE "/^.{1}g/p; /^.{13}g/p" | wc -l
echo +rlllll | sed -nE "/^.{1}l/p; /^.{6}l/p" | wc -l
echo +pdjjtcqwbqtpfkjbwgq | sed -nE "/^.{3}j/p; /^.{7}j/p" | wc -l
echo +zzhsnjrhrzzfrqszdhdg | sed -nE "/^.{7}z/p; /^.{17}z/p" | wc -l
echo +xnvnhnrn | sed -nE "/^.{6}n/p; /^.{7}n/p" | wc -l
echo +rrrrrrzr | sed -nE "/^.{6}r/p; /^.{7}r/p" | wc -l
echo +ccmcccc | sed -nE "/^.{2}c/p; /^.{3}c/p" | wc -l
echo +vvdv | sed -nE "/^.{2}v/p; /^.{3}v/p" | wc -l
echo +mlfffshbfdff | sed -nE "/^.{3}f/p; /^.{9}f/p" | wc -l
echo +dfvkltvjvvvvx | sed -nE "/^.{11}v/p; /^.{13}v/p" | wc -l
echo +mqrccccbccbgcccccvc | sed -nE "/^.{12}c/p; /^.{13}c/p" | wc -l
echo +wwwwwwwwwwwwcwtww | sed -nE "/^.{9}w/p; /^.{13}w/p" | wc -l
echo +pdvgddtmvwdkvdtzf | sed -nE "/^.{6}d/p; /^.{8}d/p" | wc -l
echo +hsssssssssdsls | sed -nE "/^.{1}s/p; /^.{9}s/p" | wc -l
echo +zbsslcd | sed -nE "/^.{1}c/p; /^.{5}c/p" | wc -l
echo +bpppppppppp | sed -nE "/^.{1}p/p; /^.{4}p/p" | wc -l
echo +sssxslsscssbqsspcs | sed -nE "/^.{13}s/p; /^.{16}s/p" | wc -l
echo +pskwpppzpppppks | sed -nE "/^.{1}p/p; /^.{10}p/p" | wc -l
echo +ccppccmcc | sed -nE "/^.{3}c/p; /^.{5}c/p" | wc -l
echo +rhbbbbbbbzbb | sed -nE "/^.{10}b/p; /^.{11}b/p" | wc -l
echo +ndhjhd | sed -nE "/^.{2}d/p; /^.{3}d/p" | wc -l
echo +sscs | sed -nE "/^.{3}s/p; /^.{4}s/p" | wc -l
echo +dtwwnt | sed -nE "/^.{5}d/p; /^.{6}d/p" | wc -l
echo +dddddddd | sed -nE "/^.{4}d/p; /^.{5}d/p" | wc -l
echo +zztzvzzzz | sed -nE "/^.{5}z/p; /^.{9}z/p" | wc -l
echo +vpqdll | sed -nE "/^.{2}v/p; /^.{6}v/p" | wc -l
echo +nxkmbkkpxkcdld | sed -nE "/^.{13}d/p; /^.{14}d/p" | wc -l
echo +ssss | sed -nE "/^.{1}s/p; /^.{3}s/p" | wc -l
echo +zzzzzzzzzzzzzbz | sed -nE "/^.{8}z/p; /^.{14}z/p" | wc -l
echo +fffnffffffftbzffpkf | sed -nE "/^.{16}f/p; /^.{17}f/p" | wc -l
echo +mtcm | sed -nE "/^.{3}m/p; /^.{4}m/p" | wc -l
echo +mrdrd | sed -nE "/^.{3}r/p; /^.{4}r/p" | wc -l
echo +ljkmhdkkkcpjzlmkkzkk | sed -nE "/^.{11}k/p; /^.{13}k/p" | wc -l
echo +tdqnxpd | sed -nE "/^.{2}d/p; /^.{3}d/p" | wc -l
echo +mrvdlthxchpvwvssqpk | sed -nE "/^.{3}h/p; /^.{7}h/p" | wc -l
echo +jjfjjvjjjjjzjsjjksxr | sed -nE "/^.{13}j/p; /^.{17}j/p" | wc -l
echo +rnnx | sed -nE "/^.{1}n/p; /^.{4}n/p" | wc -l
echo +mmmmzmxfmm | sed -nE "/^.{7}m/p; /^.{10}m/p" | wc -l
echo +lrrvrrrrm | sed -nE "/^.{1}r/p; /^.{6}r/p" | wc -l
echo +rrrdrrrrrrrrrkblrr | sed -nE "/^.{4}r/p; /^.{18}r/p" | wc -l
echo +kkkkkkl | sed -nE "/^.{6}k/p; /^.{7}k/p" | wc -l
echo +vmnfvvvvmcmlh | sed -nE "/^.{4}v/p; /^.{6}v/p" | wc -l
echo +jgcgggkbbmgbs | sed -nE "/^.{6}g/p; /^.{9}g/p" | wc -l
echo +ttcfwtgjtcttv | sed -nE "/^.{7}t/p; /^.{8}t/p" | wc -l
echo +tjjj | sed -nE "/^.{3}j/p; /^.{4}j/p" | wc -l
